#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: AITask_ClearBB

#include "Basic.hpp"


namespace SDK::Params
{

// Function AITask_ClearBB.AITask_ClearBB_C.ExecuteUbergraph_AITask_ClearBB
// 0x0030 (0x0030 - 0x0000)
struct AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36DF[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-69 ])
	class AActor*                                 K2Node_Event_OwnerActor;                           // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AAIController*                          K2Node_DynamicCast_AsAI_____;                      // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36E0[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UBlackboardComponent*                   CallFunc_GetBlackboard_ReturnValue;                // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB) == 0x000008, "Wrong alignment on AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB");
static_assert(sizeof(AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB) == 0x000030, "Wrong size on AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB");
static_assert(offsetof(AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB, EntryPoint) == 0x000000, "Member 'AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB::EntryPoint' has a wrong offset!");
static_assert(offsetof(AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB, K2Node_Event_OwnerActor) == 0x000008, "Member 'AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB::K2Node_Event_OwnerActor' has a wrong offset!");
static_assert(offsetof(AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB, K2Node_DynamicCast_AsAI_____) == 0x000010, "Member 'AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB::K2Node_DynamicCast_AsAI_____' has a wrong offset!");
static_assert(offsetof(AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB, CallFunc_GetBlackboard_ReturnValue) == 0x000020, "Member 'AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB::CallFunc_GetBlackboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'AITask_ClearBB_C_ExecuteUbergraph_AITask_ClearBB::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function AITask_ClearBB.AITask_ClearBB_C.ReceiveExecute
// 0x0008 (0x0008 - 0x0000)
struct AITask_ClearBB_C_ReceiveExecute final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AITask_ClearBB_C_ReceiveExecute) == 0x000008, "Wrong alignment on AITask_ClearBB_C_ReceiveExecute");
static_assert(sizeof(AITask_ClearBB_C_ReceiveExecute) == 0x000008, "Wrong size on AITask_ClearBB_C_ReceiveExecute");
static_assert(offsetof(AITask_ClearBB_C_ReceiveExecute, OwnerActor) == 0x000000, "Member 'AITask_ClearBB_C_ReceiveExecute::OwnerActor' has a wrong offset!");

}

