#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Annihilation_HUD_Reviver_Chara_Notify

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function Annihilation_HUD_Reviver_Chara_Notify.Annihilation_HUD_Reviver_Chara_Notify_C.ExecuteUbergraph_Annihilation_HUD_Reviver_Chara_Notify
// 0x0004 (0x0004 - 0x0000)
struct Annihilation_HUD_Reviver_Chara_Notify_C_ExecuteUbergraph_Annihilation_HUD_Reviver_Chara_Notify final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Annihilation_HUD_Reviver_Chara_Notify_C_ExecuteUbergraph_Annihilation_HUD_Reviver_Chara_Notify) == 0x000004, "Wrong alignment on Annihilation_HUD_Reviver_Chara_Notify_C_ExecuteUbergraph_Annihilation_HUD_Reviver_Chara_Notify");
static_assert(sizeof(Annihilation_HUD_Reviver_Chara_Notify_C_ExecuteUbergraph_Annihilation_HUD_Reviver_Chara_Notify) == 0x000004, "Wrong size on Annihilation_HUD_Reviver_Chara_Notify_C_ExecuteUbergraph_Annihilation_HUD_Reviver_Chara_Notify");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_ExecuteUbergraph_Annihilation_HUD_Reviver_Chara_Notify, EntryPoint) == 0x000000, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_ExecuteUbergraph_Annihilation_HUD_Reviver_Chara_Notify::EntryPoint' has a wrong offset!");

// Function Annihilation_HUD_Reviver_Chara_Notify.Annihilation_HUD_Reviver_Chara_Notify_C.Get_TXT_CountDown_Text_0
// 0x0038 (0x0038 - 0x0000)
struct Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35F0[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0020(0x0018)()
};
static_assert(alignof(Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0) == 0x000008, "Wrong alignment on Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0");
static_assert(sizeof(Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0) == 0x000038, "Wrong size on Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0, ReturnValue) == 0x000000, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0, CallFunc_Conv_IntToText_ReturnValue) == 0x000020, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_Get_TXT_CountDown_Text_0::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

// Function Annihilation_HUD_Reviver_Chara_Notify.Annihilation_HUD_Reviver_Chara_Notify_C.SetImage
// 0x0240 (0x0240 - 0x0000)
struct Annihilation_HUD_Reviver_Chara_Notify_C_SetImage final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35F1[0x6];                                     // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-69 ])
	class UTexture2D*                             CallFunc_GetPortraitIcon_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue; // 0x0010(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35F2[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue;           // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_As____2D;                       // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35F3[0x7];                                     // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetCharaIconByType_ReturnValue;           // 0x0058(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	struct FSlateBrush                            CallFunc_MakeBrushFromTexture_ReturnValue;         // 0x0080(0x00D0)()
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue_1;         // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             K2Node_DynamicCast_As____2D_1;                     // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35F4[0xF];                                     // 0x0161(0x000F)(Fixing Size After Last Property [ Dumper-69 ])
	struct FSlateBrush                            CallFunc_MakeBrushFromTexture_ReturnValue_1;       // 0x0170(0x00D0)()
};
static_assert(alignof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage) == 0x000010, "Wrong alignment on Annihilation_HUD_Reviver_Chara_Notify_C_SetImage");
static_assert(sizeof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage) == 0x000240, "Wrong size on Annihilation_HUD_Reviver_Chara_Notify_C_SetImage");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_IsValid_ReturnValue) == 0x000000, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_IsValid_ReturnValue_1) == 0x000001, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_GetPortraitIcon_ReturnValue) == 0x000008, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_GetPortraitIcon_ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue) == 0x000010, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000038, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_LoadAsset_Blocking_ReturnValue) == 0x000040, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_LoadAsset_Blocking_ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, K2Node_DynamicCast_As____2D) == 0x000048, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::K2Node_DynamicCast_As____2D' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_GetCharaIconByType_ReturnValue) == 0x000058, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_GetCharaIconByType_ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_MakeBrushFromTexture_ReturnValue) == 0x000080, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_MakeBrushFromTexture_ReturnValue' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_LoadAsset_Blocking_ReturnValue_1) == 0x000150, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_LoadAsset_Blocking_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, K2Node_DynamicCast_As____2D_1) == 0x000158, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::K2Node_DynamicCast_As____2D_1' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, K2Node_DynamicCast_bSuccess_1) == 0x000160, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Annihilation_HUD_Reviver_Chara_Notify_C_SetImage, CallFunc_MakeBrushFromTexture_ReturnValue_1) == 0x000170, "Member 'Annihilation_HUD_Reviver_Chara_Notify_C_SetImage::CallFunc_MakeBrushFromTexture_ReturnValue_1' has a wrong offset!");

}

