#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Btn_BSPlus

#include "Basic.hpp"

#include "Btn_BSPlus_classes.hpp"
#include "Btn_BSPlus_parameters.hpp"


namespace SDK
{

// Function Btn_BSPlus.Btn_BSPlus_C.UseBSPlus
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    _use_bs_plus                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBtn_BSPlus_C::UseBSPlus(bool _use_bs_plus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Btn_BSPlus_C", "UseBSPlus");

	Params::Btn_BSPlus_C_UseBSPlus Parms{};

	Parms._use_bs_plus = _use_bs_plus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Btn_BSPlus.Btn_BSPlus_C.OnShowBSPlus_Detail
// (Public, BlueprintCallable, BlueprintEvent)

void UBtn_BSPlus_C::OnShowBSPlus_Detail()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Btn_BSPlus_C", "OnShowBSPlus_Detail");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Btn_BSPlus.Btn_BSPlus_C.OnGoToShop
// (Public, BlueprintCallable, BlueprintEvent)

void UBtn_BSPlus_C::OnGoToShop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Btn_BSPlus_C", "OnGoToShop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Btn_BSPlus.Btn_BSPlus_C.GetTooltip_BSPlus
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UBtn_BSPlus_C::GetTooltip_BSPlus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Btn_BSPlus_C", "GetTooltip_BSPlus");

	Params::Btn_BSPlus_C_GetTooltip_BSPlus Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Btn_BSPlus.Btn_BSPlus_C.ExecuteUbergraph_Btn_BSPlus
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBtn_BSPlus_C::ExecuteUbergraph_Btn_BSPlus(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Btn_BSPlus_C", "ExecuteUbergraph_Btn_BSPlus");

	Params::Btn_BSPlus_C_ExecuteUbergraph_Btn_BSPlus Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Btn_BSPlus.Btn_BSPlus_C.BndEvt__Btn_BSPlus_RadioButton_216_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBtn_BSPlus_C::BndEvt__Btn_BSPlus_RadioButton_216_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Btn_BSPlus_C", "BndEvt__Btn_BSPlus_RadioButton_216_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Btn_BSPlus.Btn_BSPlus_C.BndEvt__Btn_BSPlus_RadioButton_216_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBtn_BSPlus_C::BndEvt__Btn_BSPlus_RadioButton_216_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Btn_BSPlus_C", "BndEvt__Btn_BSPlus_RadioButton_216_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

