#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Cam_Mesh_BP_Gun

#include "Basic.hpp"

#include "Cam_Mesh_BP_Gun_classes.hpp"
#include "Cam_Mesh_BP_Gun_parameters.hpp"


namespace SDK
{

// Function Cam_Mesh_BP_Gun.Cam_Mesh_BP_Gun_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACam_Mesh_BP_Gun_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Cam_Mesh_BP_Gun_C", "ReceiveTick");

	Params::Cam_Mesh_BP_Gun_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Cam_Mesh_BP_Gun.Cam_Mesh_BP_Gun_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACam_Mesh_BP_Gun_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Cam_Mesh_BP_Gun_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Cam_Mesh_BP_Gun.Cam_Mesh_BP_Gun_C.ExecuteUbergraph_Cam_Mesh_BP_Gun
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACam_Mesh_BP_Gun_C::ExecuteUbergraph_Cam_Mesh_BP_Gun(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Cam_Mesh_BP_Gun_C", "ExecuteUbergraph_Cam_Mesh_BP_Gun");

	Params::Cam_Mesh_BP_Gun_C_ExecuteUbergraph_Cam_Mesh_BP_Gun Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

