#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Challenge_MissionEntry

#include "Basic.hpp"

#include "Stigma_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Challenge_MissionEntry.Challenge_MissionEntry_C.ExecuteUbergraph_Challenge_MissionEntry
// 0x0004 (0x0004 - 0x0000)
struct Challenge_MissionEntry_C_ExecuteUbergraph_Challenge_MissionEntry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Challenge_MissionEntry_C_ExecuteUbergraph_Challenge_MissionEntry) == 0x000004, "Wrong alignment on Challenge_MissionEntry_C_ExecuteUbergraph_Challenge_MissionEntry");
static_assert(sizeof(Challenge_MissionEntry_C_ExecuteUbergraph_Challenge_MissionEntry) == 0x000004, "Wrong size on Challenge_MissionEntry_C_ExecuteUbergraph_Challenge_MissionEntry");
static_assert(offsetof(Challenge_MissionEntry_C_ExecuteUbergraph_Challenge_MissionEntry, EntryPoint) == 0x000000, "Member 'Challenge_MissionEntry_C_ExecuteUbergraph_Challenge_MissionEntry::EntryPoint' has a wrong offset!");

// Function Challenge_MissionEntry.Challenge_MissionEntry_C.ShouldHideDetailValue
// 0x0030 (0x0030 - 0x0000)
struct Challenge_MissionEntry_C_ShouldHideDetailValue final
{
public:
	TArray<class UMissionCondition*>              NewParam;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          Out;                                               // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38E4[0x3];                                     // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-69 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMissionCondition*                      CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_FailOnCalled_ReturnValue;                 // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38E5[0x2];                                     // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-69 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Challenge_MissionEntry_C_ShouldHideDetailValue) == 0x000008, "Wrong alignment on Challenge_MissionEntry_C_ShouldHideDetailValue");
static_assert(sizeof(Challenge_MissionEntry_C_ShouldHideDetailValue) == 0x000030, "Wrong size on Challenge_MissionEntry_C_ShouldHideDetailValue");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, NewParam) == 0x000000, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::NewParam' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, Out) == 0x000010, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::Out' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, CallFunc_Array_Length_ReturnValue) == 0x000014, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, Temp_int_Array_Index_Variable) == 0x000018, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, Temp_int_Loop_Counter_Variable) == 0x00001C, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, CallFunc_Array_Get_Item) == 0x000020, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, CallFunc_FailOnCalled_ReturnValue) == 0x000028, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::CallFunc_FailOnCalled_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, CallFunc_Less_IntInt_ReturnValue) == 0x000029, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_ShouldHideDetailValue, CallFunc_Add_IntInt_ReturnValue) == 0x00002C, "Member 'Challenge_MissionEntry_C_ShouldHideDetailValue::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

// Function Challenge_MissionEntry.Challenge_MissionEntry_C.UpdateByMission
// 0x02F0 (0x02F0 - 0x0000)
struct Challenge_MissionEntry_C_UpdateByMission final
{
public:
	class FText                                   DetailValueText;                                   // 0x0000(0x0018)(Edit, BlueprintVisible)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38E6[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	struct FItemID_Mission                        CallFunc_GetMissionID_ReturnValue;                 // 0x0020(0x0010)(HasGetValueTypeHash)
	struct FMissionDefine                         CallFunc_GetMissionDefineByID_ReturnValue;         // 0x0030(0x01A0)(ConstParm)
	TArray<class UMissionCondition*>              CallFunc_GetAllConditions_ReturnValue;             // 0x01D0(0x0010)(ReferenceParm)
	bool                                          CallFunc_ShouldHideDetailValue_Out;                // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38E7[0x7];                                     // 0x01E1(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue;              // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x01F0(0x0050)(HasGetValueTypeHash)
	class FText                                   CallFunc_GetDisplayMission_ReturnValue;            // 0x0240(0x0018)()
	int64                                         CallFunc_Conv_IntToInt64_ReturnValue_1;            // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0260(0x0050)(HasGetValueTypeHash)
	class FText                                   CallFunc_AppendText_ReturnValue;                   // 0x02B0(0x0018)()
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x02C8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x02D8(0x0018)()
};
static_assert(alignof(Challenge_MissionEntry_C_UpdateByMission) == 0x000008, "Wrong alignment on Challenge_MissionEntry_C_UpdateByMission");
static_assert(sizeof(Challenge_MissionEntry_C_UpdateByMission) == 0x0002F0, "Wrong size on Challenge_MissionEntry_C_UpdateByMission");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, DetailValueText) == 0x000000, "Member 'Challenge_MissionEntry_C_UpdateByMission::DetailValueText' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_IsValid_ReturnValue) == 0x000018, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_GetMissionID_ReturnValue) == 0x000020, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_GetMissionID_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_GetMissionDefineByID_ReturnValue) == 0x000030, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_GetMissionDefineByID_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_GetAllConditions_ReturnValue) == 0x0001D0, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_GetAllConditions_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_ShouldHideDetailValue_Out) == 0x0001E0, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_ShouldHideDetailValue_Out' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_Conv_IntToInt64_ReturnValue) == 0x0001E8, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_Conv_IntToInt64_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, K2Node_MakeStruct_FormatArgumentData) == 0x0001F0, "Member 'Challenge_MissionEntry_C_UpdateByMission::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_GetDisplayMission_ReturnValue) == 0x000240, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_GetDisplayMission_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_Conv_IntToInt64_ReturnValue_1) == 0x000258, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_Conv_IntToInt64_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, K2Node_MakeStruct_FormatArgumentData_1) == 0x000260, "Member 'Challenge_MissionEntry_C_UpdateByMission::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_AppendText_ReturnValue) == 0x0002B0, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_AppendText_ReturnValue' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, K2Node_MakeArray_Array) == 0x0002C8, "Member 'Challenge_MissionEntry_C_UpdateByMission::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Challenge_MissionEntry_C_UpdateByMission, CallFunc_Format_ReturnValue) == 0x0002D8, "Member 'Challenge_MissionEntry_C_UpdateByMission::CallFunc_Format_ReturnValue' has a wrong offset!");

}

