#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: CharaBase_BP

#include "Basic.hpp"

#include "CharaBase_BP_classes.hpp"
#include "CharaBase_BP_parameters.hpp"


namespace SDK
{

// Function CharaBase_BP.CharaBase_BP_C.DEBUG_GetDamageViewerClass
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TSubclassOf<class UDebug_DamageViewerComponent>ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

TSubclassOf<class UDebug_DamageViewerComponent> ACharaBase_BP_C::DEBUG_GetDamageViewerClass()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "DEBUG_GetDamageViewerClass");

	Params::CharaBase_BP_C_DEBUG_GetDamageViewerClass Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function CharaBase_BP.CharaBase_BP_C.ExecuteUbergraph_CharaBase_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACharaBase_BP_C::ExecuteUbergraph_CharaBase_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "ExecuteUbergraph_CharaBase_BP");

	Params::CharaBase_BP_C_ExecuteUbergraph_CharaBase_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharaBase_BP.CharaBase_BP_C.InpActEvt_Equals_K2Node_InputKeyEvent_1
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ACharaBase_BP_C::InpActEvt_Equals_K2Node_InputKeyEvent_1(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "InpActEvt_Equals_K2Node_InputKeyEvent_1");

	Params::CharaBase_BP_C_InpActEvt_Equals_K2Node_InputKeyEvent_1 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharaBase_BP.CharaBase_BP_C.InpActEvt_Equals_K2Node_InputKeyEvent_2
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ACharaBase_BP_C::InpActEvt_Equals_K2Node_InputKeyEvent_2(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "InpActEvt_Equals_K2Node_InputKeyEvent_2");

	Params::CharaBase_BP_C_InpActEvt_Equals_K2Node_InputKeyEvent_2 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharaBase_BP.CharaBase_BP_C.InpActEvt_F11_K2Node_InputKeyEvent_3
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ACharaBase_BP_C::InpActEvt_F11_K2Node_InputKeyEvent_3(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "InpActEvt_F11_K2Node_InputKeyEvent_3");

	Params::CharaBase_BP_C_InpActEvt_F11_K2Node_InputKeyEvent_3 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharaBase_BP.CharaBase_BP_C.InpActEvt_F11_K2Node_InputKeyEvent_4
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ACharaBase_BP_C::InpActEvt_F11_K2Node_InputKeyEvent_4(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "InpActEvt_F11_K2Node_InputKeyEvent_4");

	Params::CharaBase_BP_C_InpActEvt_F11_K2Node_InputKeyEvent_4 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharaBase_BP.CharaBase_BP_C.InpActEvt_G_K2Node_InputKeyEvent_0
// (BlueprintEvent)
// Parameters:
// struct FKey                             Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ACharaBase_BP_C::InpActEvt_G_K2Node_InputKeyEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "InpActEvt_G_K2Node_InputKeyEvent_0");

	Params::CharaBase_BP_C_InpActEvt_G_K2Node_InputKeyEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CharaBase_BP.CharaBase_BP_C.OnDamaged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)

void ACharaBase_BP_C::OnDamaged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "OnDamaged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CharaBase_BP.CharaBase_BP_C.ResetForRespawn
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ACharaBase_BP_C::ResetForRespawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CharaBase_BP_C", "ResetForRespawn");

	Params::CharaBase_BP_C_ResetForRespawn Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

