#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: CharaBase_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Stigma_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CharaBase_BP.CharaBase_BP_C
// 0x0040 (0x3690 - 0x3650)
class ACharaBase_BP_C : public ACharaBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x3650(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UObjectPool*                            ObjectPool;                                        // 0x3658(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAC_DynamicSmears_BPG_C*                AC_DynamicSmears_BPG;                              // 0x3660(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkinnedDecalSampler*                   SkinnedDecalSampler;                               // 0x3668(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPropJointComponent*                    PropJoint;                                         // 0x3670(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        PickupPivot;                                       // 0x3678(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnDamaged;                                         // 0x3680(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	TSubclassOf<class UDebug_DamageViewerComponent> DEBUG_GetDamageViewerClass();
	void ExecuteUbergraph_CharaBase_BP(int32 EntryPoint);
	void InpActEvt_Equals_K2Node_InputKeyEvent_1(const struct FKey& Key);
	void InpActEvt_Equals_K2Node_InputKeyEvent_2(const struct FKey& Key);
	void InpActEvt_F11_K2Node_InputKeyEvent_3(const struct FKey& Key);
	void InpActEvt_F11_K2Node_InputKeyEvent_4(const struct FKey& Key);
	void InpActEvt_G_K2Node_InputKeyEvent_0(const struct FKey& Key);
	void OnDamaged__DelegateSignature();
	bool ResetForRespawn();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CharaBase_BP_C">();
	}
	static class ACharaBase_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACharaBase_BP_C>();
	}
};
static_assert(alignof(ACharaBase_BP_C) == 0x000010, "Wrong alignment on ACharaBase_BP_C");
static_assert(sizeof(ACharaBase_BP_C) == 0x003690, "Wrong size on ACharaBase_BP_C");
static_assert(offsetof(ACharaBase_BP_C, UberGraphFrame) == 0x003650, "Member 'ACharaBase_BP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ACharaBase_BP_C, ObjectPool) == 0x003658, "Member 'ACharaBase_BP_C::ObjectPool' has a wrong offset!");
static_assert(offsetof(ACharaBase_BP_C, AC_DynamicSmears_BPG) == 0x003660, "Member 'ACharaBase_BP_C::AC_DynamicSmears_BPG' has a wrong offset!");
static_assert(offsetof(ACharaBase_BP_C, SkinnedDecalSampler) == 0x003668, "Member 'ACharaBase_BP_C::SkinnedDecalSampler' has a wrong offset!");
static_assert(offsetof(ACharaBase_BP_C, PropJoint) == 0x003670, "Member 'ACharaBase_BP_C::PropJoint' has a wrong offset!");
static_assert(offsetof(ACharaBase_BP_C, PickupPivot) == 0x003678, "Member 'ACharaBase_BP_C::PickupPivot' has a wrong offset!");
static_assert(offsetof(ACharaBase_BP_C, OnDamaged) == 0x003680, "Member 'ACharaBase_BP_C::OnDamaged' has a wrong offset!");

}

