#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Ctrl_SearchUser_LVItem

#include "Basic.hpp"

#include "Ctrl_SearchUser_LVItem_classes.hpp"
#include "Ctrl_SearchUser_LVItem_parameters.hpp"


namespace SDK
{

// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.SetFriendShipText
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             _text                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UCtrl_SearchUser_LVItem_C::SetFriendShipText(class FText& _text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "SetFriendShipText");

	Params::Ctrl_SearchUser_LVItem_C_SetFriendShipText Parms{};

	Parms._text = std::move(_text);

	UObject::ProcessEvent(Func, &Parms);

	_text = std::move(Parms._text);
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UCtrl_SearchUser_LVItem_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "OnMouseEnter");

	Params::Ctrl_SearchUser_LVItem_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UCtrl_SearchUser_LVItem_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "OnListItemObjectSet");

	Params::Ctrl_SearchUser_LVItem_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.OnClick__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBriefUser*                       _search_user_data                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UCtrl_SearchUser_LVItem_C::OnClick__DelegateSignature(class UBriefUser* _search_user_data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "OnClick__DelegateSignature");

	Params::Ctrl_SearchUser_LVItem_C_OnClick__DelegateSignature Parms{};

	Parms._search_user_data = _search_user_data;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.OnBIND_BackgroundColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UCtrl_SearchUser_LVItem_C::OnBIND_BackgroundColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "OnBIND_BackgroundColor");

	Params::Ctrl_SearchUser_LVItem_C_OnBIND_BackgroundColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.InitBySearchUserData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserProfile*                     _search_user                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UCtrl_SearchUser_LVItem_C::InitBySearchUserData(class UUserProfile*& _search_user)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "InitBySearchUserData");

	Params::Ctrl_SearchUser_LVItem_C_InitBySearchUserData Parms{};

	Parms._search_user = _search_user;

	UObject::ProcessEvent(Func, &Parms);

	_search_user = Parms._search_user;
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.GetTooltip
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UCtrl_SearchUser_LVItem_C::GetTooltip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "GetTooltip");

	Params::Ctrl_SearchUser_LVItem_C_GetTooltip Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.GetSearchUserData
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserProfile*                     _user_search_data                                      (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UCtrl_SearchUser_LVItem_C::GetSearchUserData(class UUserProfile** _user_search_data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "GetSearchUserData");

	Params::Ctrl_SearchUser_LVItem_C_GetSearchUserData Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (_user_search_data != nullptr)
		*_user_search_data = Parms._user_search_data;
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.ExecuteUbergraph_Ctrl_SearchUser_LVItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_SearchUser_LVItem_C::ExecuteUbergraph_Ctrl_SearchUser_LVItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "ExecuteUbergraph_Ctrl_SearchUser_LVItem");

	Params::Ctrl_SearchUser_LVItem_C_ExecuteUbergraph_Ctrl_SearchUser_LVItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_SearchUser_LVItem_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "BP_OnItemSelectionChanged");

	Params::Ctrl_SearchUser_LVItem_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_SearchUser_LVItem_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "BP_OnItemExpansionChanged");

	Params::Ctrl_SearchUser_LVItem_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UCtrl_SearchUser_LVItem_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ctrl_SearchUser_LVItem.Ctrl_SearchUser_LVItem_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FKeyEvent                        InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UCtrl_SearchUser_LVItem_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_SearchUser_LVItem_C", "OnKeyDown");

	Params::Ctrl_SearchUser_LVItem_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

