#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Ctrl_NavigationStepper

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Ctrl_NavigationStepper.Ctrl_NavigationStepper_C.ExecuteUbergraph_Ctrl_NavigationStepper
// 0x0004 (0x0004 - 0x0000)
struct Ctrl_NavigationStepper_C_ExecuteUbergraph_Ctrl_NavigationStepper final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Ctrl_NavigationStepper_C_ExecuteUbergraph_Ctrl_NavigationStepper) == 0x000004, "Wrong alignment on Ctrl_NavigationStepper_C_ExecuteUbergraph_Ctrl_NavigationStepper");
static_assert(sizeof(Ctrl_NavigationStepper_C_ExecuteUbergraph_Ctrl_NavigationStepper) == 0x000004, "Wrong size on Ctrl_NavigationStepper_C_ExecuteUbergraph_Ctrl_NavigationStepper");
static_assert(offsetof(Ctrl_NavigationStepper_C_ExecuteUbergraph_Ctrl_NavigationStepper, EntryPoint) == 0x000000, "Member 'Ctrl_NavigationStepper_C_ExecuteUbergraph_Ctrl_NavigationStepper::EntryPoint' has a wrong offset!");

// Function Ctrl_NavigationStepper.Ctrl_NavigationStepper_C.GetNotSelectedEntrySlotBtnColor
// 0x0010 (0x0010 - 0x0000)
struct Ctrl_NavigationStepper_C_GetNotSelectedEntrySlotBtnColor final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Ctrl_NavigationStepper_C_GetNotSelectedEntrySlotBtnColor) == 0x000004, "Wrong alignment on Ctrl_NavigationStepper_C_GetNotSelectedEntrySlotBtnColor");
static_assert(sizeof(Ctrl_NavigationStepper_C_GetNotSelectedEntrySlotBtnColor) == 0x000010, "Wrong size on Ctrl_NavigationStepper_C_GetNotSelectedEntrySlotBtnColor");
static_assert(offsetof(Ctrl_NavigationStepper_C_GetNotSelectedEntrySlotBtnColor, ReturnValue) == 0x000000, "Member 'Ctrl_NavigationStepper_C_GetNotSelectedEntrySlotBtnColor::ReturnValue' has a wrong offset!");

// Function Ctrl_NavigationStepper.Ctrl_NavigationStepper_C.GetSelectedEntrySlotBtnColor
// 0x0010 (0x0010 - 0x0000)
struct Ctrl_NavigationStepper_C_GetSelectedEntrySlotBtnColor final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Ctrl_NavigationStepper_C_GetSelectedEntrySlotBtnColor) == 0x000004, "Wrong alignment on Ctrl_NavigationStepper_C_GetSelectedEntrySlotBtnColor");
static_assert(sizeof(Ctrl_NavigationStepper_C_GetSelectedEntrySlotBtnColor) == 0x000010, "Wrong size on Ctrl_NavigationStepper_C_GetSelectedEntrySlotBtnColor");
static_assert(offsetof(Ctrl_NavigationStepper_C_GetSelectedEntrySlotBtnColor, ReturnValue) == 0x000000, "Member 'Ctrl_NavigationStepper_C_GetSelectedEntrySlotBtnColor::ReturnValue' has a wrong offset!");

// Function Ctrl_NavigationStepper.Ctrl_NavigationStepper_C.OnSynchronizeProperties
// 0x0001 (0x0001 - 0x0000)
struct Ctrl_NavigationStepper_C_OnSynchronizeProperties final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Ctrl_NavigationStepper_C_OnSynchronizeProperties) == 0x000001, "Wrong alignment on Ctrl_NavigationStepper_C_OnSynchronizeProperties");
static_assert(sizeof(Ctrl_NavigationStepper_C_OnSynchronizeProperties) == 0x000001, "Wrong size on Ctrl_NavigationStepper_C_OnSynchronizeProperties");
static_assert(offsetof(Ctrl_NavigationStepper_C_OnSynchronizeProperties, ReturnValue) == 0x000000, "Member 'Ctrl_NavigationStepper_C_OnSynchronizeProperties::ReturnValue' has a wrong offset!");

}

