#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Ctrl_EnemyPlayer

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Ctrl_EnemyPlayer.Ctrl_EnemyPlayer_C
// 0x0010 (0x02D0 - 0x02C0)
class UCtrl_EnemyPlayer_C final : public UUserWidget
{
public:
	class UImage*                                 IMG_Confirmed;                                     // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class AMatchServicedPlayerState*              PlayerState;                                       // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BindPlayer(class AMatchServicedPlayerState* _player_state);
	void UpdateAll();
	void UpdateState();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ctrl_EnemyPlayer_C">();
	}
	static class UCtrl_EnemyPlayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCtrl_EnemyPlayer_C>();
	}
};
static_assert(alignof(UCtrl_EnemyPlayer_C) == 0x000008, "Wrong alignment on UCtrl_EnemyPlayer_C");
static_assert(sizeof(UCtrl_EnemyPlayer_C) == 0x0002D0, "Wrong size on UCtrl_EnemyPlayer_C");
static_assert(offsetof(UCtrl_EnemyPlayer_C, IMG_Confirmed) == 0x0002C0, "Member 'UCtrl_EnemyPlayer_C::IMG_Confirmed' has a wrong offset!");
static_assert(offsetof(UCtrl_EnemyPlayer_C, PlayerState) == 0x0002C8, "Member 'UCtrl_EnemyPlayer_C::PlayerState' has a wrong offset!");

}

