#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Ctrl_HUD_FlyBullet

#include "Basic.hpp"

#include "Ctrl_HUD_FlyBullet_classes.hpp"
#include "Ctrl_HUD_FlyBullet_parameters.hpp"


namespace SDK
{

// Function Ctrl_HUD_FlyBullet.Ctrl_HUD_FlyBullet_C.ExecuteUbergraph_Ctrl_HUD_FlyBullet
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_HUD_FlyBullet_C::ExecuteUbergraph_Ctrl_HUD_FlyBullet(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_HUD_FlyBullet_C", "ExecuteUbergraph_Ctrl_HUD_FlyBullet");

	Params::Ctrl_HUD_FlyBullet_C_ExecuteUbergraph_Ctrl_HUD_FlyBullet Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_HUD_FlyBullet.Ctrl_HUD_FlyBullet_C.StartFly
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  _fly_angle                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  _fly_power                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  _rotation_power                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_HUD_FlyBullet_C::StartFly(double _fly_angle, double _fly_power, double _rotation_power)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_HUD_FlyBullet_C", "StartFly");

	Params::Ctrl_HUD_FlyBullet_C_StartFly Parms{};

	Parms._fly_angle = _fly_angle;
	Parms._fly_power = _fly_power;
	Parms._rotation_power = _rotation_power;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_HUD_FlyBullet.Ctrl_HUD_FlyBullet_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_HUD_FlyBullet_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_HUD_FlyBullet_C", "Tick");

	Params::Ctrl_HUD_FlyBullet_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_HUD_FlyBullet.Ctrl_HUD_FlyBullet_C.UpdateFlyBullet
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  _delta                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_HUD_FlyBullet_C::UpdateFlyBullet(double _delta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_HUD_FlyBullet_C", "UpdateFlyBullet");

	Params::Ctrl_HUD_FlyBullet_C_UpdateFlyBullet Parms{};

	Parms._delta = _delta;

	UObject::ProcessEvent(Func, &Parms);
}

}

