#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Ctrl_PlayerResultRow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Stigma_structs.hpp"
#include "Stigma_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Ctrl_PlayerResultRow.Ctrl_PlayerResultRow_C
// 0x0028 (0x0648 - 0x0620)
class UCtrl_PlayerResultRow_C final : public UUI_PlayerResultItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0620(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_93;                                          // 0x0628(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IMG_NonHoverMask;                                  // 0x0630(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class AMatchServicedPlayerState*              ReportedPS;                                        // 0x0638(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UUI_ToastMessageContainer_C*            TempToastContainer;                                // 0x0640(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void AddFriend();
	void AddTempToastMsg(const class FString& _msg);
	void BndEvt__Ctrl_PlayerResultRow_BTN_AddFriend_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__Ctrl_PlayerResultRow_Button_66_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__Ctrl_PlayerResultRow_ProfileCard_K2Node_ComponentBoundEvent_3_OnAck_AboutFriend__DelegateSignature(const class FString& _toast_msg);
	void ExecuteUbergraph_Ctrl_PlayerResultRow(int32 EntryPoint);
	class UWidget* Get_ProfileCard_ToolTipWidget();
	struct FNetReply OnAck_AskFriend(EResultCode _rcode, const struct FACK_Friend& _ack);
	struct FNetReply OnAck_UserReportJWT(EResultCode _rcode, const struct FACK_GetUserReportJWT& _ack);
	ESlateVisibility OnGetVisibility_NonHover();
	void OnUpdateUI_ProfileCard();
	void SendUserReport();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ctrl_PlayerResultRow_C">();
	}
	static class UCtrl_PlayerResultRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCtrl_PlayerResultRow_C>();
	}
};
static_assert(alignof(UCtrl_PlayerResultRow_C) == 0x000008, "Wrong alignment on UCtrl_PlayerResultRow_C");
static_assert(sizeof(UCtrl_PlayerResultRow_C) == 0x000648, "Wrong size on UCtrl_PlayerResultRow_C");
static_assert(offsetof(UCtrl_PlayerResultRow_C, UberGraphFrame) == 0x000620, "Member 'UCtrl_PlayerResultRow_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UCtrl_PlayerResultRow_C, Image_93) == 0x000628, "Member 'UCtrl_PlayerResultRow_C::Image_93' has a wrong offset!");
static_assert(offsetof(UCtrl_PlayerResultRow_C, IMG_NonHoverMask) == 0x000630, "Member 'UCtrl_PlayerResultRow_C::IMG_NonHoverMask' has a wrong offset!");
static_assert(offsetof(UCtrl_PlayerResultRow_C, ReportedPS) == 0x000638, "Member 'UCtrl_PlayerResultRow_C::ReportedPS' has a wrong offset!");
static_assert(offsetof(UCtrl_PlayerResultRow_C, TempToastContainer) == 0x000640, "Member 'UCtrl_PlayerResultRow_C::TempToastContainer' has a wrong offset!");

}

