#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Ctrl_TextCheckBox

#include "Basic.hpp"

#include "Ctrl_TextCheckBox_classes.hpp"
#include "Ctrl_TextCheckBox_parameters.hpp"


namespace SDK
{

// Function Ctrl_TextCheckBox.Ctrl_TextCheckBox_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCtrl_TextCheckBox_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_TextCheckBox_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ctrl_TextCheckBox.Ctrl_TextCheckBox_C.CustomEvent
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCtrl_TextCheckBoxBase*           _check_box                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class FName                             Param__id                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    _is_checked                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_TextCheckBox_C::CustomEvent(const class UCtrl_TextCheckBoxBase* _check_box, const class FName& Param__id, bool _is_checked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_TextCheckBox_C", "CustomEvent");

	Params::Ctrl_TextCheckBox_C_CustomEvent Parms{};

	Parms._check_box = _check_box;
	Parms.Param__id = Param__id;
	Parms._is_checked = _is_checked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_TextCheckBox.Ctrl_TextCheckBox_C.ExecuteUbergraph_Ctrl_TextCheckBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_TextCheckBox_C::ExecuteUbergraph_Ctrl_TextCheckBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_TextCheckBox_C", "ExecuteUbergraph_Ctrl_TextCheckBox");

	Params::Ctrl_TextCheckBox_C_ExecuteUbergraph_Ctrl_TextCheckBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_TextCheckBox.Ctrl_TextCheckBox_C.OnCheckStateChanged__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Param_IsChecked                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_TextCheckBox_C::OnCheckStateChanged__DelegateSignature(bool Param_IsChecked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_TextCheckBox_C", "OnCheckStateChanged__DelegateSignature");

	Params::Ctrl_TextCheckBox_C_OnCheckStateChanged__DelegateSignature Parms{};

	Parms.Param_IsChecked = Param_IsChecked;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ctrl_TextCheckBox.Ctrl_TextCheckBox_C.OnSynchronizeProperties
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UCtrl_TextCheckBox_C::OnSynchronizeProperties()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_TextCheckBox_C", "OnSynchronizeProperties");

	Params::Ctrl_TextCheckBox_C_OnSynchronizeProperties Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Ctrl_TextCheckBox.Ctrl_TextCheckBox_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCtrl_TextCheckBox_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ctrl_TextCheckBox_C", "PreConstruct");

	Params::Ctrl_TextCheckBox_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

