#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Ctrl_DebugStateRow

#include "Basic.hpp"


namespace SDK::Params
{

// Function Ctrl_DebugStateRow.Ctrl_DebugStateRow_C.OnSynchronizeProperties
// 0x0001 (0x0001 - 0x0000)
struct Ctrl_DebugStateRow_C_OnSynchronizeProperties final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Ctrl_DebugStateRow_C_OnSynchronizeProperties) == 0x000001, "Wrong alignment on Ctrl_DebugStateRow_C_OnSynchronizeProperties");
static_assert(sizeof(Ctrl_DebugStateRow_C_OnSynchronizeProperties) == 0x000001, "Wrong size on Ctrl_DebugStateRow_C_OnSynchronizeProperties");
static_assert(offsetof(Ctrl_DebugStateRow_C_OnSynchronizeProperties, ReturnValue) == 0x000000, "Member 'Ctrl_DebugStateRow_C_OnSynchronizeProperties::ReturnValue' has a wrong offset!");

// Function Ctrl_DebugStateRow.Ctrl_DebugStateRow_C.SetValues
// 0x0060 (0x0060 - 0x0000)
struct Ctrl_DebugStateRow_C_SetValues final
{
public:
	class FText                                   _current;                                          // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   _total;                                            // 0x0018(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   _base;                                             // 0x0030(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   _boost;                                            // 0x0048(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(Ctrl_DebugStateRow_C_SetValues) == 0x000008, "Wrong alignment on Ctrl_DebugStateRow_C_SetValues");
static_assert(sizeof(Ctrl_DebugStateRow_C_SetValues) == 0x000060, "Wrong size on Ctrl_DebugStateRow_C_SetValues");
static_assert(offsetof(Ctrl_DebugStateRow_C_SetValues, _current) == 0x000000, "Member 'Ctrl_DebugStateRow_C_SetValues::_current' has a wrong offset!");
static_assert(offsetof(Ctrl_DebugStateRow_C_SetValues, _total) == 0x000018, "Member 'Ctrl_DebugStateRow_C_SetValues::_total' has a wrong offset!");
static_assert(offsetof(Ctrl_DebugStateRow_C_SetValues, _base) == 0x000030, "Member 'Ctrl_DebugStateRow_C_SetValues::_base' has a wrong offset!");
static_assert(offsetof(Ctrl_DebugStateRow_C_SetValues, _boost) == 0x000048, "Member 'Ctrl_DebugStateRow_C_SetValues::_boost' has a wrong offset!");

}

