#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: GrayHeavy_Post_AnimBP

#include "Basic.hpp"

#include "KawaiiPhysics_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass GrayHeavy_Post_AnimBP.GrayHeavy_Post_AnimBP_C
// 0x1340 (0x1690 - 0x0350)
class UGrayHeavy_Post_AnimBP_C final : public UAnimInstance
{
public:
	uint8                                         Pad_3EE2[0x8];                                     // 0x0348(0x0008)(Fixing Size After Last Property [ Dumper-69 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0358(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0360(0x0008)()
	uint8                                         Pad_3EE3[0x8];                                     // 0x0368(0x0008)(Fixing Size After Last Property [ Dumper-69 ])
	struct FAnimNode_KawaiiPhysics                AnimGraphNode_KawaiiPhysics_1;                     // 0x0370(0x0790)()
	struct FAnimNode_SpringBone                   AnimGraphNode_SpringBone_1;                        // 0x0B00(0x0168)()
	struct FAnimNode_SpringBone                   AnimGraphNode_SpringBone;                          // 0x0C68(0x0168)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0DD0(0x00B8)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0E88(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0EA8(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0EC8(0x0020)()
	uint8                                         Pad_3EE4[0x8];                                     // 0x0EE8(0x0008)(Fixing Size After Last Property [ Dumper-69 ])
	struct FAnimNode_KawaiiPhysics                AnimGraphNode_KawaiiPhysics;                       // 0x0EF0(0x0790)()
	double                                        _RightHand_ScaleAlpha;                             // 0x1680(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GrayHeavy_Post_AnimBP(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* Param_AnimGraph);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GrayHeavy_Post_AnimBP_C">();
	}
	static class UGrayHeavy_Post_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGrayHeavy_Post_AnimBP_C>();
	}
};
static_assert(alignof(UGrayHeavy_Post_AnimBP_C) == 0x000010, "Wrong alignment on UGrayHeavy_Post_AnimBP_C");
static_assert(sizeof(UGrayHeavy_Post_AnimBP_C) == 0x001690, "Wrong size on UGrayHeavy_Post_AnimBP_C");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, UberGraphFrame) == 0x000350, "Member 'UGrayHeavy_Post_AnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimBlueprintExtension_PropertyAccess) == 0x000358, "Member 'UGrayHeavy_Post_AnimBP_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimBlueprintExtension_Base) == 0x000360, "Member 'UGrayHeavy_Post_AnimBP_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimGraphNode_KawaiiPhysics_1) == 0x000370, "Member 'UGrayHeavy_Post_AnimBP_C::AnimGraphNode_KawaiiPhysics_1' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimGraphNode_SpringBone_1) == 0x000B00, "Member 'UGrayHeavy_Post_AnimBP_C::AnimGraphNode_SpringBone_1' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimGraphNode_SpringBone) == 0x000C68, "Member 'UGrayHeavy_Post_AnimBP_C::AnimGraphNode_SpringBone' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimGraphNode_LinkedInputPose) == 0x000DD0, "Member 'UGrayHeavy_Post_AnimBP_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimGraphNode_Root) == 0x000E88, "Member 'UGrayHeavy_Post_AnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimGraphNode_LocalToComponentSpace) == 0x000EA8, "Member 'UGrayHeavy_Post_AnimBP_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimGraphNode_ComponentToLocalSpace) == 0x000EC8, "Member 'UGrayHeavy_Post_AnimBP_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, AnimGraphNode_KawaiiPhysics) == 0x000EF0, "Member 'UGrayHeavy_Post_AnimBP_C::AnimGraphNode_KawaiiPhysics' has a wrong offset!");
static_assert(offsetof(UGrayHeavy_Post_AnimBP_C, _RightHand_ScaleAlpha) == 0x001680, "Member 'UGrayHeavy_Post_AnimBP_C::_RightHand_ScaleAlpha' has a wrong offset!");

}

