#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Hand_Les_BP

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Hand_Les_BP.Hand_Les_BP_C
// 0x0020 (0x02B8 - 0x0298)
class AHand_Les_BP_C final : public AActor
{
public:
	class USkeletalMeshComponent*                 Hand_Fac_Les_SET;                                  // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Hand_Msk_Les_Fac;                                  // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Hand_Bdy_Les;                                      // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Hand_Les_BP_C">();
	}
	static class AHand_Les_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHand_Les_BP_C>();
	}
};
static_assert(alignof(AHand_Les_BP_C) == 0x000008, "Wrong alignment on AHand_Les_BP_C");
static_assert(sizeof(AHand_Les_BP_C) == 0x0002B8, "Wrong size on AHand_Les_BP_C");
static_assert(offsetof(AHand_Les_BP_C, Hand_Fac_Les_SET) == 0x000298, "Member 'AHand_Les_BP_C::Hand_Fac_Les_SET' has a wrong offset!");
static_assert(offsetof(AHand_Les_BP_C, Hand_Msk_Les_Fac) == 0x0002A0, "Member 'AHand_Les_BP_C::Hand_Msk_Les_Fac' has a wrong offset!");
static_assert(offsetof(AHand_Les_BP_C, Hand_Bdy_Les) == 0x0002A8, "Member 'AHand_Les_BP_C::Hand_Bdy_Les' has a wrong offset!");
static_assert(offsetof(AHand_Les_BP_C, DefaultSceneRoot) == 0x0002B0, "Member 'AHand_Les_BP_C::DefaultSceneRoot' has a wrong offset!");

}

