#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Item_TierRewardsRow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "Stigma_structs.hpp"


namespace SDK::Params
{

// Function Item_TierRewardsRow.Item_TierRewardsRow_C.OnListItemObjectSet
// 0x0008 (0x0008 - 0x0000)
struct Item_TierRewardsRow_C_OnListItemObjectSet final
{
public:
	class UObject*                                ListItemObject;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Item_TierRewardsRow_C_OnListItemObjectSet) == 0x000008, "Wrong alignment on Item_TierRewardsRow_C_OnListItemObjectSet");
static_assert(sizeof(Item_TierRewardsRow_C_OnListItemObjectSet) == 0x000008, "Wrong size on Item_TierRewardsRow_C_OnListItemObjectSet");
static_assert(offsetof(Item_TierRewardsRow_C_OnListItemObjectSet, ListItemObject) == 0x000000, "Member 'Item_TierRewardsRow_C_OnListItemObjectSet::ListItemObject' has a wrong offset!");

// Function Item_TierRewardsRow.Item_TierRewardsRow_C.ExecuteUbergraph_Item_TierRewardsRow
// 0x02A8 (0x02A8 - 0x0000)
struct Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_40B6[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-69 ])
	class UUI_Comp_RewardItem_C*                  CallFunc_Create_ReturnValue;                       // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsExpanded;                          // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsSelected;                          // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40B7[0x2];                                     // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-69 ])
	class UObject*                                K2Node_Event_ListItemObject;                       // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULVData_TierRewards_C*                  K2Node_DynamicCast_AsLVData_Tier_Rewards;          // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40B8[0x7];                                     // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	struct FConfig_Tier                           CallFunc_GetTierDefine_ReturnValue;                // 0x0040(0x00D8)(ConstParm)
	struct FSeasonReward                          CallFunc_GetSeasonRewardByTier_ReturnValue;        // 0x0118(0x0018)(ConstParm)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40B9[0x7];                                     // 0x0131(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	struct FRewardItem                            CallFunc_Array_Get_Item;                           // 0x0138(0x0018)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0154(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0155(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40BA[0x2];                                     // 0x0156(0x0002)(Fixing Size After Last Property [ Dumper-69 ])
	class FText                                   CallFunc_AsPercent_Float_ReturnValue;              // 0x0158(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0170(0x0050)(HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40BB[0x7];                                     // 0x01C1(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01C8(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01D8(0x0018)()
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x01F0(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0208(0x0050)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0258(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0268(0x0018)()
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0280(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0284(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40BC[0x3];                                     // 0x0285(0x0003)(Fixing Size After Last Property [ Dumper-69 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0288(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_40BD[0x4];                                     // 0x028C(0x0004)(Fixing Size After Last Property [ Dumper-69 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x0290(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast; // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow) == 0x000008, "Wrong alignment on Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow");
static_assert(sizeof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow) == 0x0002A8, "Wrong size on Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, EntryPoint) == 0x000000, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::EntryPoint' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_MakeStruct_Margin) == 0x000004, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Create_ReturnValue) == 0x000018, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, Temp_int_Array_Index_Variable) == 0x000020, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_Event_bIsExpanded) == 0x000024, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_Event_bIsExpanded' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_Event_bIsSelected) == 0x000025, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_Event_bIsSelected' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_Event_ListItemObject) == 0x000028, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_Event_ListItemObject' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_DynamicCast_AsLVData_Tier_Rewards) == 0x000030, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_DynamicCast_AsLVData_Tier_Rewards' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_GetTierDefine_ReturnValue) == 0x000040, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_GetTierDefine_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_GetSeasonRewardByTier_ReturnValue) == 0x000118, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_GetSeasonRewardByTier_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000130, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Array_Get_Item) == 0x000138, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Array_Length_ReturnValue) == 0x000150, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_EqualEqual_DoubleDouble_ReturnValue) == 0x000154, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_EqualEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_BooleanOR_ReturnValue) == 0x000155, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_AsPercent_Float_ReturnValue) == 0x000158, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_AsPercent_Float_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_MakeStruct_FormatArgumentData) == 0x000170, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Greater_IntInt_ReturnValue) == 0x0001C0, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_MakeArray_Array) == 0x0001C8, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Format_ReturnValue) == 0x0001D8, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Conv_IntToText_ReturnValue) == 0x0001F0, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_MakeStruct_FormatArgumentData_1) == 0x000208, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, K2Node_MakeArray_Array_1) == 0x000258, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Format_ReturnValue_1) == 0x000268, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, Temp_int_Loop_Counter_Variable) == 0x000280, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Less_IntInt_ReturnValue) == 0x000284, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_Add_IntInt_ReturnValue) == 0x000288, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x000290, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast) == 0x000298, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow, CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast) == 0x0002A0, "Member 'Item_TierRewardsRow_C_ExecuteUbergraph_Item_TierRewardsRow::CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function Item_TierRewardsRow.Item_TierRewardsRow_C.BP_OnItemSelectionChanged
// 0x0001 (0x0001 - 0x0000)
struct Item_TierRewardsRow_C_BP_OnItemSelectionChanged final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Item_TierRewardsRow_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong alignment on Item_TierRewardsRow_C_BP_OnItemSelectionChanged");
static_assert(sizeof(Item_TierRewardsRow_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong size on Item_TierRewardsRow_C_BP_OnItemSelectionChanged");
static_assert(offsetof(Item_TierRewardsRow_C_BP_OnItemSelectionChanged, bIsSelected) == 0x000000, "Member 'Item_TierRewardsRow_C_BP_OnItemSelectionChanged::bIsSelected' has a wrong offset!");

// Function Item_TierRewardsRow.Item_TierRewardsRow_C.BP_OnItemExpansionChanged
// 0x0001 (0x0001 - 0x0000)
struct Item_TierRewardsRow_C_BP_OnItemExpansionChanged final
{
public:
	bool                                          bIsExpanded;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Item_TierRewardsRow_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong alignment on Item_TierRewardsRow_C_BP_OnItemExpansionChanged");
static_assert(sizeof(Item_TierRewardsRow_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong size on Item_TierRewardsRow_C_BP_OnItemExpansionChanged");
static_assert(offsetof(Item_TierRewardsRow_C_BP_OnItemExpansionChanged, bIsExpanded) == 0x000000, "Member 'Item_TierRewardsRow_C_BP_OnItemExpansionChanged::bIsExpanded' has a wrong offset!");

}

