#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Item_GunPreset

#include "Basic.hpp"

#include "Item_GunPreset_classes.hpp"
#include "Item_GunPreset_parameters.hpp"


namespace SDK
{

// Function Item_GunPreset.Item_GunPreset_C.Get Visibility Ovl Checked
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UItem_GunPreset_C::Get_Visibility_Ovl_Checked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_GunPreset_C", "Get Visibility Ovl Checked");

	Params::Item_GunPreset_C_Get_Visibility_Ovl_Checked Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Item_GunPreset.Item_GunPreset_C.SetGunObject
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UGunObject*                       _gun_object                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UItem_GunPreset_C::SetGunObject(class UGunObject* _gun_object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_GunPreset_C", "SetGunObject");

	Params::Item_GunPreset_C_SetGunObject Parms{};

	Parms._gun_object = _gun_object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Item_GunPreset.Item_GunPreset_C.SetMasterIdx
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   _idx                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UItem_GunPreset_C::SetMasterIdx(int32 _idx)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Item_GunPreset_C", "SetMasterIdx");

	Params::Item_GunPreset_C_SetMasterIdx Parms{};

	Parms._idx = _idx;

	UObject::ProcessEvent(Func, &Parms);
}

}

