#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Marker_Chara_BP

#include "Basic.hpp"

#include "Marker_Chara_BP_classes.hpp"
#include "Marker_Chara_BP_parameters.hpp"


namespace SDK
{

// Function Marker_Chara_BP.Marker_Chara_BP_C.ChangeNewState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECharaMarkerState                       _new_state                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMarker_Chara_BP_C::ChangeNewState(ECharaMarkerState _new_state)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "ChangeNewState");

	Params::Marker_Chara_BP_C_ChangeNewState Parms{};

	Parms._new_state = _new_state;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.ChangeState_AliveState
// (Public, BlueprintCallable, BlueprintEvent)

void UMarker_Chara_BP_C::ChangeState_AliveState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "ChangeState_AliveState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.ChangeState_BountyTarget
// (Public, BlueprintCallable, BlueprintEvent)

void UMarker_Chara_BP_C::ChangeState_BountyTarget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "ChangeState_BountyTarget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.ChangeState_Dead
// (Public, BlueprintCallable, BlueprintEvent)

void UMarker_Chara_BP_C::ChangeState_Dead()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "ChangeState_Dead");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.ChangeVisibilityWRTState
// (Public, BlueprintCallable, BlueprintEvent)

void UMarker_Chara_BP_C::ChangeVisibilityWRTState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "ChangeVisibilityWRTState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMarker_Chara_BP_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.DriveState
// (Public, BlueprintCallable, BlueprintEvent)

void UMarker_Chara_BP_C::DriveState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "DriveState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.ExecuteUbergraph_Marker_Chara_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMarker_Chara_BP_C::ExecuteUbergraph_Marker_Chara_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "ExecuteUbergraph_Marker_Chara_BP");

	Params::Marker_Chara_BP_C_ExecuteUbergraph_Marker_Chara_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.GetTeamColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// EPlayerSide                             _side                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     _color                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMarker_Chara_BP_C::GetTeamColor(EPlayerSide _side, struct FLinearColor* _color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "GetTeamColor");

	Params::Marker_Chara_BP_C_GetTeamColor Parms{};

	Parms._side = _side;

	UObject::ProcessEvent(Func, &Parms);

	if (_color != nullptr)
		*_color = std::move(Parms._color);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.IsSpectatedChara
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    _is                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMarker_Chara_BP_C::IsSpectatedChara(bool* _is)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "IsSpectatedChara");

	Params::Marker_Chara_BP_C_IsSpectatedChara Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (_is != nullptr)
		*_is = Parms._is;
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.OnBindActor
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           _Actor                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UMarker_Chara_BP_C::OnBindActor(class AActor* _Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "OnBindActor");

	Params::Marker_Chara_BP_C_OnBindActor Parms{};

	Parms._Actor = _Actor;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.OnTick
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor)
// float                                   _delta                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UMarker_Chara_BP_C::OnTick(const struct FGeometry& MyGeometry, float _delta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "OnTick");

	Params::Marker_Chara_BP_C_OnTick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms._delta = _delta;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.UpdateSpectating
// (Public, BlueprintCallable, BlueprintEvent)

void UMarker_Chara_BP_C::UpdateSpectating()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "UpdateSpectating");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Marker_Chara_BP.Marker_Chara_BP_C.GetLocalPlayerState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class APlayerState*                     _player_state                                          (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMarker_Chara_BP_C::GetLocalPlayerState(class APlayerState** _player_state) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Marker_Chara_BP_C", "GetLocalPlayerState");

	Params::Marker_Chara_BP_C_GetLocalPlayerState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (_player_state != nullptr)
		*_player_state = Parms._player_state;
}

}

