#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Move_NavFilter

#include "Basic.hpp"

#include "NavigationSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Move_NavFilter.Move_NavFilter_C
// 0x0000 (0x0048 - 0x0048)
class UMove_NavFilter_C final : public UNavigationQueryFilter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Move_NavFilter_C">();
	}
	static class UMove_NavFilter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMove_NavFilter_C>();
	}
};
static_assert(alignof(UMove_NavFilter_C) == 0x000008, "Wrong alignment on UMove_NavFilter_C");
static_assert(sizeof(UMove_NavFilter_C) == 0x000048, "Wrong size on UMove_NavFilter_C");

}

