#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: PAGE_Main

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "Stigma_structs.hpp"
#include "Stigma_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PAGE_Main.PAGE_Main_C
// 0x0140 (0x0650 - 0x0510)
class UPAGE_Main_C final : public UUI_LobbyPage
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0510(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_BattlePassBriefContainer_C*         BattlePassBriefContainer;                          // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBtn_BSPlus_C*                          Btn_BSPlus;                                        // 0x0520(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCtrl_CommonButtonBase_C*               BTN_CancelMatch;                                   // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBtn_CompetitionBrief_C*                Btn_Competition;                                   // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCtrl_CommonButtonBase_C*               BTN_LeaveParty;                                    // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                BTN_Profile;                                       // 0x0540(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCtrl_CommonButton_Intensity_C*         Btn_WelcomeMatch;                                  // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton_ProfileCardLocalUser_C*         Button_ProfileCardLocalUser;                       // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCircularThrobber*                      CircularThrobber_67;                               // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCtrl_PlayButton_C*                     Ctrl_PlayButton;                                   // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCtrl_WebBrowser_C*                     Ctrl_WebBrowser;                                   // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         H_ActiveFunc_Container;                            // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         H_GMFunc_Container;                                // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_205;                                         // 0x0588(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Ovl_MatchMakingState;                              // 0x0590(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPanel_Player_C*                        Panel_Player_0;                                    // 0x0598(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPanel_Player_C*                        Panel_Player_1;                                    // 0x05A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPanel_Player_C*                        Panel_Player_2;                                    // 0x05A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UProfileCard_LocalUser_C*               ProfileCard_LocalUser;                             // 0x05B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_Match_PartyMember;                             // 0x05B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_MatchElapsed;                                  // 0x05C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_MatchingStatus;                                // 0x05C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_MissionBrief_C*                     UI_Mission;                                        // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_TextBubble_C*                       UI_TrackMissionEventBubble;                        // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWIDGET_FunctionWidget_C*               WIDGET_FunctionWidget;                             // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWIDGET_FunctionWidget_C*               WIDGET_FunctionWidget_1;                           // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWIDGET_FunctionWidget_C*               WIDGET_FunctionWidget_2;                           // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWIDGET_FunctionWidget_C*               WIDGET_FunctionWidget_3;                           // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnPlayButton;                                      // 0x0600(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_             OnCancelMatch;                                     // 0x0610(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class UPanel_Player_C*>                PanelPlayerList;                                   // 0x0620(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                          EnableDebugFeatures;                               // 0x0630(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3B29[0x7];                                     // 0x0631(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UClass*                                 BattlePassBriefClass;                              // 0x0638(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              LastMatchElapsed;                                  // 0x0640(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          _IsMatchMaking;                                    // 0x0648(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          _CanControlMatching;                               // 0x0649(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UpdateWaitingMatchStatusText(bool _force_update);
	void UpdateTutorialState();
	void UpdateState();
	void UpdatePartySlots();
	void UpdateGMFunction();
	void UpdateActiveFunction();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	EEventCasterResponse ShowTrackMissionBubble(const class FName& _event_name, const struct FCastedEvent& _event);
	void SetVisibility_BTN_CancelMatch();
	void SetMatchStatusText(const class FText& _text);
	void SetEnableAllPartyPlayers(bool _enable);
	void OnUpdateWebBrowser();
	void OnUpdateUser(EUserEvent _event);
	void OnTrainingMapJumpMsgBoxClicked(class UPopupBase* _popup, class FName _button_id);
	void OnTick(double _delta);
	void OnPlayPVP();
	void OnPlayButton__DelegateSignature(const class FString& Map_name);
	bool OnParty_MemberDeleted(const class UBriefParty* _party, const struct FUserID& _user_id);
	bool OnParty_MemberAdded(const class UBriefParty* _party, const class UUserProfile* _member);
	bool OnParty_LeaderUpdated(const struct FUserID& _leader_id);
	bool OnParty_Exited();
	bool OnParty_Entered(const class UBriefParty* _party);
	bool OnParty_CharacterUpdated(const struct FUserID& _user_id, const struct FCharSpec& _chara);
	EEventCasterResponse OnMissionUpdateEvent(const class FName& _event_name, const struct FCastedEvent& _event);
	bool OnMatchChanged();
	void OnLoad_User();
	void OnExitPartyConfirm(class UPopupBase* _popup, class FName _button_id);
	void OnDestruct();
	void OnConfirmWelcomeMatch(const class UPopupBase* _popup, class FName _ctrl_id);
	void OnCancelMatch__DelegateSignature();
	struct FNetReply OnAck_PartyDelete(EResultCode _rcode, const struct FACK_PartyDelete& _ack);
	struct FNetReply OnACK_CancelMatchMaking(EResultCode _rcode, const struct FApiResult& _ack);
	void On_Update_Profile();
	void Mark_WelcomeMatchRecommended();
	void InpActEvt_Slash_K2Node_InputDebugKeyEvent_0(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void Init();
	void HasRecommended_WelcomeMatch(bool* _asked);
	void GetWelcomeMatchKey(class FString* _Key);
	class UWidget* GetTooltip_WelcomeMatch();
	void ExecuteUbergraph_PAGE_Main(int32 EntryPoint);
	void EnableCtrls(bool _enable);
	void Destruct();
	struct FNetReply DEBUG_ACK_UserReport(EResultCode _rcode, const struct FACK_GetUserReportJWT& _ack);
	void Construct();
	void CheckMissionAutoReward();
	void CancelMatchMaking();
	void BndEvt__UI_LobbyPlayPage_Panel_Player_2_K2Node_ComponentBoundEvent_9_OnInvitePartyBtnClick__DelegateSignature();
	void BndEvt__UI_LobbyPlayPage_Panel_Player_1_K2Node_ComponentBoundEvent_7_OnInvitePartyBtnClick__DelegateSignature();
	void BndEvt__UI_LobbyPlayPage_Panel_Player_0_K2Node_ComponentBoundEvent_8_OnInvitePartyBtnClick__DelegateSignature();
	void BndEvt__PAGE_Main_UI_Mission_K2Node_ComponentBoundEvent_4_ShowBeginnerMissionBubble__DelegateSignature(bool Show);
	void BndEvt__PAGE_Main_Ctrl_PlayButton_K2Node_ComponentBoundEvent_1_DM_OnSelectStart__DelegateSignature(class UAnimatableWidget* _widget, bool _select);
	void BndEvt__PAGE_Main_Ctrl_CommonButtonBase_K2Node_ComponentBoundEvent_3_DM_OnSelectEnd__DelegateSignature(class UAnimatableWidget* _widget, bool _select);
	void BndEvt__PAGE_Main_BTN_WelcomeMatch_K2Node_ComponentBoundEvent_2_DM_OnSelectEnd__DelegateSignature(class UAnimatableWidget* _widget, bool _select);
	void BndEvt__PAGE_Main_BTN_LeaveParty2_K2Node_ComponentBoundEvent_0_DM_OnSelectEnd__DelegateSignature(class UAnimatableWidget* _widget, bool _select);
	void AutoRewardMission(class UAnimatableWidget* _widget);

	void GetPlayerCtrl(int32 _idx, class UPanel_Player_C** _ctrl) const;
	void GetGameInst(class UStigmaGameInstance** _game_inst) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PAGE_Main_C">();
	}
	static class UPAGE_Main_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPAGE_Main_C>();
	}
};
static_assert(alignof(UPAGE_Main_C) == 0x000008, "Wrong alignment on UPAGE_Main_C");
static_assert(sizeof(UPAGE_Main_C) == 0x000650, "Wrong size on UPAGE_Main_C");
static_assert(offsetof(UPAGE_Main_C, UberGraphFrame) == 0x000510, "Member 'UPAGE_Main_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, BattlePassBriefContainer) == 0x000518, "Member 'UPAGE_Main_C::BattlePassBriefContainer' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Btn_BSPlus) == 0x000520, "Member 'UPAGE_Main_C::Btn_BSPlus' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, BTN_CancelMatch) == 0x000528, "Member 'UPAGE_Main_C::BTN_CancelMatch' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Btn_Competition) == 0x000530, "Member 'UPAGE_Main_C::Btn_Competition' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, BTN_LeaveParty) == 0x000538, "Member 'UPAGE_Main_C::BTN_LeaveParty' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, BTN_Profile) == 0x000540, "Member 'UPAGE_Main_C::BTN_Profile' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Btn_WelcomeMatch) == 0x000548, "Member 'UPAGE_Main_C::Btn_WelcomeMatch' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Button_ProfileCardLocalUser) == 0x000550, "Member 'UPAGE_Main_C::Button_ProfileCardLocalUser' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, CircularThrobber_67) == 0x000558, "Member 'UPAGE_Main_C::CircularThrobber_67' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Ctrl_PlayButton) == 0x000560, "Member 'UPAGE_Main_C::Ctrl_PlayButton' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Ctrl_WebBrowser) == 0x000568, "Member 'UPAGE_Main_C::Ctrl_WebBrowser' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, H_ActiveFunc_Container) == 0x000570, "Member 'UPAGE_Main_C::H_ActiveFunc_Container' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, H_GMFunc_Container) == 0x000578, "Member 'UPAGE_Main_C::H_GMFunc_Container' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Image) == 0x000580, "Member 'UPAGE_Main_C::Image' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Image_205) == 0x000588, "Member 'UPAGE_Main_C::Image_205' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Ovl_MatchMakingState) == 0x000590, "Member 'UPAGE_Main_C::Ovl_MatchMakingState' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Panel_Player_0) == 0x000598, "Member 'UPAGE_Main_C::Panel_Player_0' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Panel_Player_1) == 0x0005A0, "Member 'UPAGE_Main_C::Panel_Player_1' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, Panel_Player_2) == 0x0005A8, "Member 'UPAGE_Main_C::Panel_Player_2' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, ProfileCard_LocalUser) == 0x0005B0, "Member 'UPAGE_Main_C::ProfileCard_LocalUser' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, TXT_Match_PartyMember) == 0x0005B8, "Member 'UPAGE_Main_C::TXT_Match_PartyMember' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, TXT_MatchElapsed) == 0x0005C0, "Member 'UPAGE_Main_C::TXT_MatchElapsed' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, TXT_MatchingStatus) == 0x0005C8, "Member 'UPAGE_Main_C::TXT_MatchingStatus' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, UI_Mission) == 0x0005D0, "Member 'UPAGE_Main_C::UI_Mission' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, UI_TrackMissionEventBubble) == 0x0005D8, "Member 'UPAGE_Main_C::UI_TrackMissionEventBubble' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, WIDGET_FunctionWidget) == 0x0005E0, "Member 'UPAGE_Main_C::WIDGET_FunctionWidget' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, WIDGET_FunctionWidget_1) == 0x0005E8, "Member 'UPAGE_Main_C::WIDGET_FunctionWidget_1' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, WIDGET_FunctionWidget_2) == 0x0005F0, "Member 'UPAGE_Main_C::WIDGET_FunctionWidget_2' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, WIDGET_FunctionWidget_3) == 0x0005F8, "Member 'UPAGE_Main_C::WIDGET_FunctionWidget_3' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, OnPlayButton) == 0x000600, "Member 'UPAGE_Main_C::OnPlayButton' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, OnCancelMatch) == 0x000610, "Member 'UPAGE_Main_C::OnCancelMatch' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, PanelPlayerList) == 0x000620, "Member 'UPAGE_Main_C::PanelPlayerList' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, EnableDebugFeatures) == 0x000630, "Member 'UPAGE_Main_C::EnableDebugFeatures' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, BattlePassBriefClass) == 0x000638, "Member 'UPAGE_Main_C::BattlePassBriefClass' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, LastMatchElapsed) == 0x000640, "Member 'UPAGE_Main_C::LastMatchElapsed' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, _IsMatchMaking) == 0x000648, "Member 'UPAGE_Main_C::_IsMatchMaking' has a wrong offset!");
static_assert(offsetof(UPAGE_Main_C, _CanControlMatching) == 0x000649, "Member 'UPAGE_Main_C::_CanControlMatching' has a wrong offset!");

}

