#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Panel_DebugState

#include "Basic.hpp"

#include "Panel_DebugState_classes.hpp"
#include "Panel_DebugState_parameters.hpp"


namespace SDK
{

// Function Panel_DebugState.Panel_DebugState_C.BindChara
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharaBase*                       _chara                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPanel_DebugState_C::BindChara(class ACharaBase* _chara)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "BindChara");

	Params::Panel_DebugState_C_BindChara Parms{};

	Parms._chara = _chara;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Panel_DebugState.Panel_DebugState_C.ExecuteUbergraph_Panel_DebugState
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPanel_DebugState_C::ExecuteUbergraph_Panel_DebugState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "ExecuteUbergraph_Panel_DebugState");

	Params::Panel_DebugState_C_ExecuteUbergraph_Panel_DebugState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Panel_DebugState.Panel_DebugState_C.OnTick
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  _delta                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPanel_DebugState_C::OnTick(double _delta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "OnTick");

	Params::Panel_DebugState_C_OnTick Parms{};

	Parms._delta = _delta;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Panel_DebugState.Panel_DebugState_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPanel_DebugState_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "Tick");

	Params::Panel_DebugState_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Panel_DebugState.Panel_DebugState_C.Update_Deviation
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UPanel_DebugState_C::Update_Deviation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "Update_Deviation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Panel_DebugState.Panel_DebugState_C.UpdateControlPower
// (Public, BlueprintCallable, BlueprintEvent)

void UPanel_DebugState_C::UpdateControlPower()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "UpdateControlPower");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Panel_DebugState.Panel_DebugState_C.UpdateRecoil
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UPanel_DebugState_C::UpdateRecoil()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "UpdateRecoil");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Panel_DebugState.Panel_DebugState_C.UpdateSpeed
// (Public, BlueprintCallable, BlueprintEvent)

void UPanel_DebugState_C::UpdateSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "UpdateSpeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Panel_DebugState.Panel_DebugState_C.UpdateValues
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FStateValues                     _values                                                (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// class UCtrl_DebugStateRow_C*            _ctrl                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UPanel_DebugState_C::UpdateValues(struct FStateValues& _values, class UCtrl_DebugStateRow_C* _ctrl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Panel_DebugState_C", "UpdateValues");

	Params::Panel_DebugState_C_UpdateValues Parms{};

	Parms._values = std::move(_values);
	Parms._ctrl = _ctrl;

	UObject::ProcessEvent(Func, &Parms);

	_values = std::move(Parms._values);
}

}

