#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Popup_Wallet

#include "Basic.hpp"

#include "Stigma_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Popup_Wallet.Popup_Wallet_C
// 0x0070 (0x0600 - 0x0590)
class UPopup_Wallet_C final : public UUI_Wallet
{
public:
	class UImage*                                 Image_98;                                          // 0x0590(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_292;                                         // 0x0598(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_392;                                         // 0x05A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem;                                // 0x05A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_1;                              // 0x05B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_2;                              // 0x05B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_3;                              // 0x05C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_4;                              // 0x05C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_5;                              // 0x05D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_6;                              // 0x05D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_7;                              // 0x05E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_8;                              // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_9;                              // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUi_Wallet_ListItem_C*                  Ui_Wallet_ListItem_10;                             // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Popup_Wallet_C">();
	}
	static class UPopup_Wallet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPopup_Wallet_C>();
	}
};
static_assert(alignof(UPopup_Wallet_C) == 0x000008, "Wrong alignment on UPopup_Wallet_C");
static_assert(sizeof(UPopup_Wallet_C) == 0x000600, "Wrong size on UPopup_Wallet_C");
static_assert(offsetof(UPopup_Wallet_C, Image_98) == 0x000590, "Member 'UPopup_Wallet_C::Image_98' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Image_292) == 0x000598, "Member 'UPopup_Wallet_C::Image_292' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Image_392) == 0x0005A0, "Member 'UPopup_Wallet_C::Image_392' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem) == 0x0005A8, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_1) == 0x0005B0, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_1' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_2) == 0x0005B8, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_2' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_3) == 0x0005C0, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_3' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_4) == 0x0005C8, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_4' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_5) == 0x0005D0, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_5' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_6) == 0x0005D8, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_6' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_7) == 0x0005E0, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_7' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_8) == 0x0005E8, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_8' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_9) == 0x0005F0, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_9' has a wrong offset!");
static_assert(offsetof(UPopup_Wallet_C, Ui_Wallet_ListItem_10) == 0x0005F8, "Member 'UPopup_Wallet_C::Ui_Wallet_ListItem_10' has a wrong offset!");

}

