#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Popup_BattlePass_Guide

#include "Basic.hpp"


namespace SDK::Params
{

// Function Popup_BattlePass_Guide.Popup_BattlePass_Guide_C.ExecuteUbergraph_Popup_BattlePass_Guide
// 0x0004 (0x0004 - 0x0000)
struct Popup_BattlePass_Guide_C_ExecuteUbergraph_Popup_BattlePass_Guide final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Popup_BattlePass_Guide_C_ExecuteUbergraph_Popup_BattlePass_Guide) == 0x000004, "Wrong alignment on Popup_BattlePass_Guide_C_ExecuteUbergraph_Popup_BattlePass_Guide");
static_assert(sizeof(Popup_BattlePass_Guide_C_ExecuteUbergraph_Popup_BattlePass_Guide) == 0x000004, "Wrong size on Popup_BattlePass_Guide_C_ExecuteUbergraph_Popup_BattlePass_Guide");
static_assert(offsetof(Popup_BattlePass_Guide_C_ExecuteUbergraph_Popup_BattlePass_Guide, EntryPoint) == 0x000000, "Member 'Popup_BattlePass_Guide_C_ExecuteUbergraph_Popup_BattlePass_Guide::EntryPoint' has a wrong offset!");

// Function Popup_BattlePass_Guide.Popup_BattlePass_Guide_C.OnSynchronizeProperties
// 0x0001 (0x0001 - 0x0000)
struct Popup_BattlePass_Guide_C_OnSynchronizeProperties final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Popup_BattlePass_Guide_C_OnSynchronizeProperties) == 0x000001, "Wrong alignment on Popup_BattlePass_Guide_C_OnSynchronizeProperties");
static_assert(sizeof(Popup_BattlePass_Guide_C_OnSynchronizeProperties) == 0x000001, "Wrong size on Popup_BattlePass_Guide_C_OnSynchronizeProperties");
static_assert(offsetof(Popup_BattlePass_Guide_C_OnSynchronizeProperties, ReturnValue) == 0x000000, "Member 'Popup_BattlePass_Guide_C_OnSynchronizeProperties::ReturnValue' has a wrong offset!");

}

