#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: ProfileCard_Kaira_PR_02

#include "Basic.hpp"

#include "ProfileCard_Kaira_PR_02_classes.hpp"
#include "ProfileCard_Kaira_PR_02_parameters.hpp"


namespace SDK
{

// Function ProfileCard_Kaira_PR_02.ProfileCard_Kaira_PR_02_C.ExecuteUbergraph_ProfileCard_Kaira_PR_02
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UProfileCard_Kaira_PR_02_C::ExecuteUbergraph_ProfileCard_Kaira_PR_02(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ProfileCard_Kaira_PR_02_C", "ExecuteUbergraph_ProfileCard_Kaira_PR_02");

	Params::ProfileCard_Kaira_PR_02_C_ExecuteUbergraph_ProfileCard_Kaira_PR_02 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

