#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: ShopGoodsHelper

#include "Basic.hpp"

#include "Stigma_structs.hpp"


namespace SDK::Params
{

// Function ShopGoodsHelper.ShopGoodsHelper_C.GetFilterText_Currency
// 0x0048 (0x0048 - 0x0000)
struct ShopGoodsHelper_C_GetFilterText_Currency final
{
public:
	uint8                                         Currency;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36F3[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   Out_text;                                          // 0x0010(0x0018)(Parm, OutParm)
	class FText                                   Value_text;                                        // 0x0028(0x0018)(Edit, BlueprintVisible)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShopGoodsHelper_C_GetFilterText_Currency) == 0x000008, "Wrong alignment on ShopGoodsHelper_C_GetFilterText_Currency");
static_assert(sizeof(ShopGoodsHelper_C_GetFilterText_Currency) == 0x000048, "Wrong size on ShopGoodsHelper_C_GetFilterText_Currency");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Currency, Currency) == 0x000000, "Member 'ShopGoodsHelper_C_GetFilterText_Currency::Currency' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Currency, __WorldContext) == 0x000008, "Member 'ShopGoodsHelper_C_GetFilterText_Currency::__WorldContext' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Currency, Out_text) == 0x000010, "Member 'ShopGoodsHelper_C_GetFilterText_Currency::Out_text' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Currency, Value_text) == 0x000028, "Member 'ShopGoodsHelper_C_GetFilterText_Currency::Value_text' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Currency, K2Node_SwitchEnum_CmpSuccess) == 0x000040, "Member 'ShopGoodsHelper_C_GetFilterText_Currency::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function ShopGoodsHelper.ShopGoodsHelper_C.GetFilterText_Misc
// 0x0048 (0x0048 - 0x0000)
struct ShopGoodsHelper_C_GetFilterText_Misc final
{
public:
	uint8                                         Misc;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36F4[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   Out_text;                                          // 0x0010(0x0018)(Parm, OutParm)
	class FText                                   Value_text;                                        // 0x0028(0x0018)(Edit, BlueprintVisible)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShopGoodsHelper_C_GetFilterText_Misc) == 0x000008, "Wrong alignment on ShopGoodsHelper_C_GetFilterText_Misc");
static_assert(sizeof(ShopGoodsHelper_C_GetFilterText_Misc) == 0x000048, "Wrong size on ShopGoodsHelper_C_GetFilterText_Misc");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Misc, Misc) == 0x000000, "Member 'ShopGoodsHelper_C_GetFilterText_Misc::Misc' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Misc, __WorldContext) == 0x000008, "Member 'ShopGoodsHelper_C_GetFilterText_Misc::__WorldContext' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Misc, Out_text) == 0x000010, "Member 'ShopGoodsHelper_C_GetFilterText_Misc::Out_text' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Misc, Value_text) == 0x000028, "Member 'ShopGoodsHelper_C_GetFilterText_Misc::Value_text' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Misc, K2Node_SwitchEnum_CmpSuccess) == 0x000040, "Member 'ShopGoodsHelper_C_GetFilterText_Misc::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function ShopGoodsHelper.ShopGoodsHelper_C.GetFilterText_Tag
// 0x0048 (0x0048 - 0x0000)
struct ShopGoodsHelper_C_GetFilterText_Tag final
{
public:
	uint8                                         Tag;                                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36F5[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   Out_text;                                          // 0x0010(0x0018)(Parm, OutParm)
	class FText                                   Value_text;                                        // 0x0028(0x0018)(Edit, BlueprintVisible)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShopGoodsHelper_C_GetFilterText_Tag) == 0x000008, "Wrong alignment on ShopGoodsHelper_C_GetFilterText_Tag");
static_assert(sizeof(ShopGoodsHelper_C_GetFilterText_Tag) == 0x000048, "Wrong size on ShopGoodsHelper_C_GetFilterText_Tag");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Tag, Tag) == 0x000000, "Member 'ShopGoodsHelper_C_GetFilterText_Tag::Tag' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Tag, __WorldContext) == 0x000008, "Member 'ShopGoodsHelper_C_GetFilterText_Tag::__WorldContext' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Tag, Out_text) == 0x000010, "Member 'ShopGoodsHelper_C_GetFilterText_Tag::Out_text' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Tag, Value_text) == 0x000028, "Member 'ShopGoodsHelper_C_GetFilterText_Tag::Value_text' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetFilterText_Tag, K2Node_SwitchEnum_CmpSuccess) == 0x000040, "Member 'ShopGoodsHelper_C_GetFilterText_Tag::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function ShopGoodsHelper.ShopGoodsHelper_C.GetLimitTypeText
// 0x0048 (0x0048 - 0x0000)
struct ShopGoodsHelper_C_GetLimitTypeText final
{
public:
	EBuyLimitType                                 LimitType;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36F6[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   Out;                                               // 0x0010(0x0018)(Parm, OutParm)
	class FText                                   LimitText;                                         // 0x0028(0x0018)(Edit, BlueprintVisible)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShopGoodsHelper_C_GetLimitTypeText) == 0x000008, "Wrong alignment on ShopGoodsHelper_C_GetLimitTypeText");
static_assert(sizeof(ShopGoodsHelper_C_GetLimitTypeText) == 0x000048, "Wrong size on ShopGoodsHelper_C_GetLimitTypeText");
static_assert(offsetof(ShopGoodsHelper_C_GetLimitTypeText, LimitType) == 0x000000, "Member 'ShopGoodsHelper_C_GetLimitTypeText::LimitType' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetLimitTypeText, __WorldContext) == 0x000008, "Member 'ShopGoodsHelper_C_GetLimitTypeText::__WorldContext' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetLimitTypeText, Out) == 0x000010, "Member 'ShopGoodsHelper_C_GetLimitTypeText::Out' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetLimitTypeText, LimitText) == 0x000028, "Member 'ShopGoodsHelper_C_GetLimitTypeText::LimitText' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_GetLimitTypeText, K2Node_SwitchEnum_CmpSuccess) == 0x000040, "Member 'ShopGoodsHelper_C_GetLimitTypeText::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function ShopGoodsHelper.ShopGoodsHelper_C.IsEqualGoodsFilter
// 0x0020 (0x0020 - 0x0000)
struct ShopGoodsHelper_C_IsEqualGoodsFilter final
{
public:
	struct FGoodsFilterInfo                       Ref1;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FGoodsFilterInfo                       Ref2;                                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	class UObject*                                __WorldContext;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Value;                                             // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ShopGoodsHelper_C_IsEqualGoodsFilter) == 0x000008, "Wrong alignment on ShopGoodsHelper_C_IsEqualGoodsFilter");
static_assert(sizeof(ShopGoodsHelper_C_IsEqualGoodsFilter) == 0x000020, "Wrong size on ShopGoodsHelper_C_IsEqualGoodsFilter");
static_assert(offsetof(ShopGoodsHelper_C_IsEqualGoodsFilter, Ref1) == 0x000000, "Member 'ShopGoodsHelper_C_IsEqualGoodsFilter::Ref1' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_IsEqualGoodsFilter, Ref2) == 0x000008, "Member 'ShopGoodsHelper_C_IsEqualGoodsFilter::Ref2' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_IsEqualGoodsFilter, __WorldContext) == 0x000010, "Member 'ShopGoodsHelper_C_IsEqualGoodsFilter::__WorldContext' has a wrong offset!");
static_assert(offsetof(ShopGoodsHelper_C_IsEqualGoodsFilter, Value) == 0x000018, "Member 'ShopGoodsHelper_C_IsEqualGoodsFilter::Value' has a wrong offset!");

}

