#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: Sim_Post_AnimBP

#include "Basic.hpp"

#include "Sim_Post_AnimBP_classes.hpp"
#include "Sim_Post_AnimBP_parameters.hpp"


namespace SDK
{

// Function Sim_Post_AnimBP.Sim_Post_AnimBP_C.ExecuteUbergraph_Sim_Post_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USim_Post_AnimBP_C::ExecuteUbergraph_Sim_Post_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sim_Post_AnimBP_C", "ExecuteUbergraph_Sim_Post_AnimBP");

	Params::Sim_Post_AnimBP_C_ExecuteUbergraph_Sim_Post_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Sim_Post_AnimBP.Sim_Post_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void USim_Post_AnimBP_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Sim_Post_AnimBP_C", "AnimGraph");

	Params::Sim_Post_AnimBP_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}

}

