#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_BoosterSlot_BP

#include "Basic.hpp"

#include "UI_BoosterSlot_BP_classes.hpp"
#include "UI_BoosterSlot_BP_parameters.hpp"


namespace SDK
{

// Function UI_BoosterSlot_BP.UI_BoosterSlot_BP_C.On Get Tooltip
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUI_BoosterSlot_BP_C::On_Get_Tooltip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BoosterSlot_BP_C", "On Get Tooltip");

	Params::UI_BoosterSlot_BP_C_On_Get_Tooltip Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_BoosterSlot_BP.UI_BoosterSlot_BP_C.OnSynchronizeProperties
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UUI_BoosterSlot_BP_C::OnSynchronizeProperties()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_BoosterSlot_BP_C", "OnSynchronizeProperties");

	Params::UI_BoosterSlot_BP_C_OnSynchronizeProperties Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

