#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_ChatBox

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function UI_ChatBox.UI_ChatBox_C.BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature");
static_assert(sizeof(UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature) == 0x000018, "Wrong size on UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature");
static_assert(offsetof(UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature, Text) == 0x000000, "Member 'UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_1_OnEditableTextChangedEvent__DelegateSignature::Text' has a wrong offset!");

// Function UI_ChatBox.UI_ChatBox_C.BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	ETextCommit                                   CommitMethod;                                      // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature) == 0x000008, "Wrong alignment on UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature");
static_assert(sizeof(UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature) == 0x000020, "Wrong size on UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature");
static_assert(offsetof(UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature, Text) == 0x000000, "Member 'UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature::Text' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature, CommitMethod) == 0x000018, "Member 'UI_ChatBox_C_BndEvt__UI_ChatBox_ChatInputBox_K2Node_ComponentBoundEvent_2_OnEditableTextCommittedEvent__DelegateSignature::CommitMethod' has a wrong offset!");

// Function UI_ChatBox.UI_ChatBox_C.ExecuteUbergraph_UI_ChatBox
// 0x0040 (0x0040 - 0x0000)
struct UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D92[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-69 ])
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x0008(0x0018)(ConstParm)
	class FText                                   K2Node_ComponentBoundEvent_Text_1;                 // 0x0020(0x0018)(ConstParm)
	ETextCommit                                   K2Node_ComponentBoundEvent_CommitMethod;           // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox) == 0x000008, "Wrong alignment on UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox");
static_assert(sizeof(UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox) == 0x000040, "Wrong size on UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox");
static_assert(offsetof(UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox, EntryPoint) == 0x000000, "Member 'UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox, K2Node_ComponentBoundEvent_Text) == 0x000008, "Member 'UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox::K2Node_ComponentBoundEvent_Text' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox, K2Node_ComponentBoundEvent_Text_1) == 0x000020, "Member 'UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox::K2Node_ComponentBoundEvent_Text_1' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox, K2Node_ComponentBoundEvent_CommitMethod) == 0x000038, "Member 'UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox::K2Node_ComponentBoundEvent_CommitMethod' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox, K2Node_SwitchEnum_CmpSuccess) == 0x000039, "Member 'UI_ChatBox_C_ExecuteUbergraph_UI_ChatBox::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function UI_ChatBox.UI_ChatBox_C.Get_H_Radio_Visibility
// 0x0020 (0x0020 - 0x0000)
struct UI_ChatBox_C_Get_H_Radio_Visibility final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D93[0x6];                                     // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-69 ])
	class AStigmaPlayerController*                CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABattlePlayerControllerBase*            K2Node_DynamicCast_AsBattle_Player_Controller_Base; // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSpectating_ReturnValue;                 // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ChatBox_C_Get_H_Radio_Visibility) == 0x000008, "Wrong alignment on UI_ChatBox_C_Get_H_Radio_Visibility");
static_assert(sizeof(UI_ChatBox_C_Get_H_Radio_Visibility) == 0x000020, "Wrong size on UI_ChatBox_C_Get_H_Radio_Visibility");
static_assert(offsetof(UI_ChatBox_C_Get_H_Radio_Visibility, ReturnValue) == 0x000000, "Member 'UI_ChatBox_C_Get_H_Radio_Visibility::ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_Get_H_Radio_Visibility, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000001, "Member 'UI_ChatBox_C_Get_H_Radio_Visibility::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_Get_H_Radio_Visibility, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000008, "Member 'UI_ChatBox_C_Get_H_Radio_Visibility::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_Get_H_Radio_Visibility, K2Node_DynamicCast_AsBattle_Player_Controller_Base) == 0x000010, "Member 'UI_ChatBox_C_Get_H_Radio_Visibility::K2Node_DynamicCast_AsBattle_Player_Controller_Base' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_Get_H_Radio_Visibility, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'UI_ChatBox_C_Get_H_Radio_Visibility::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_Get_H_Radio_Visibility, CallFunc_IsSpectating_ReturnValue) == 0x000019, "Member 'UI_ChatBox_C_Get_H_Radio_Visibility::CallFunc_IsSpectating_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_Get_H_Radio_Visibility, CallFunc_BooleanOR_ReturnValue) == 0x00001A, "Member 'UI_ChatBox_C_Get_H_Radio_Visibility::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function UI_ChatBox.UI_ChatBox_C.OnSynchronizeProperties
// 0x0018 (0x0018 - 0x0000)
struct UI_ChatBox_C_OnSynchronizeProperties final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D94[0x7];                                     // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class AStigmaPlayerController*                CallFunc_GetLocalPlayerController_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ChatBox_C_OnSynchronizeProperties) == 0x000008, "Wrong alignment on UI_ChatBox_C_OnSynchronizeProperties");
static_assert(sizeof(UI_ChatBox_C_OnSynchronizeProperties) == 0x000018, "Wrong size on UI_ChatBox_C_OnSynchronizeProperties");
static_assert(offsetof(UI_ChatBox_C_OnSynchronizeProperties, ReturnValue) == 0x000000, "Member 'UI_ChatBox_C_OnSynchronizeProperties::ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_OnSynchronizeProperties, CallFunc_GetLocalPlayerController_ReturnValue) == 0x000008, "Member 'UI_ChatBox_C_OnSynchronizeProperties::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_ChatBox_C_OnSynchronizeProperties, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'UI_ChatBox_C_OnSynchronizeProperties::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

