#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_GN_MissionSuccessContainer

#include "Basic.hpp"

#include "Stigma_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_GN_MissionSuccessContainer.UI_GN_MissionSuccessContainer_C
// 0x0010 (0x0560 - 0x0550)
class UUI_GN_MissionSuccessContainer_C final : public UUI_GameNotify_MissionSuccessContainer
{
public:
	class UUI_MissionSuccessSlot_C*               UI_MissionSuccessSlot;                             // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_GN_MissionSuccessContainer_C">();
	}
	static class UUI_GN_MissionSuccessContainer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_GN_MissionSuccessContainer_C>();
	}
};
static_assert(alignof(UUI_GN_MissionSuccessContainer_C) == 0x000010, "Wrong alignment on UUI_GN_MissionSuccessContainer_C");
static_assert(sizeof(UUI_GN_MissionSuccessContainer_C) == 0x000560, "Wrong size on UUI_GN_MissionSuccessContainer_C");
static_assert(offsetof(UUI_GN_MissionSuccessContainer_C, UI_MissionSuccessSlot) == 0x000550, "Member 'UUI_GN_MissionSuccessContainer_C::UI_MissionSuccessSlot' has a wrong offset!");

}

