#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_HitRadar

#include "Basic.hpp"

#include "UI_HitRadar_classes.hpp"
#include "UI_HitRadar_parameters.hpp"


namespace SDK
{

// Function UI_HitRadar.UI_HitRadar_C.AddHit
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FHitData                         _hit                                                   (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UUI_HitRadar_C::AddHit(const struct FHitData& _hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "AddHit");

	Params::UI_HitRadar_C_AddHit Parms{};

	Parms._hit = std::move(_hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HitRadar.UI_HitRadar_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_HitRadar_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HitRadar.UI_HitRadar_C.EnableShow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    _show                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HitRadar_C::EnableShow(bool _show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "EnableShow");

	Params::UI_HitRadar_C_EnableShow Parms{};

	Parms._show = _show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HitRadar.UI_HitRadar_C.ExecuteUbergraph_UI_HitRadar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HitRadar_C::ExecuteUbergraph_UI_HitRadar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "ExecuteUbergraph_UI_HitRadar");

	Params::UI_HitRadar_C_ExecuteUbergraph_UI_HitRadar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HitRadar.UI_HitRadar_C.Init
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HitRadar_C::Init()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "Init");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HitRadar.UI_HitRadar_C.OnSynchronizeProperties
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UUI_HitRadar_C::OnSynchronizeProperties()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "OnSynchronizeProperties");

	Params::UI_HitRadar_C_OnSynchronizeProperties Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_HitRadar.UI_HitRadar_C.OnTick
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  _delta                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HitRadar_C::OnTick(double _delta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "OnTick");

	Params::UI_HitRadar_C_OnTick Parms{};

	Parms._delta = _delta;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HitRadar.UI_HitRadar_C.Reset
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_HitRadar_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_HitRadar.UI_HitRadar_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_HitRadar_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "Tick");

	Params::UI_HitRadar_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_HitRadar.UI_HitRadar_C.GetCtrls
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FHitData                         _hit                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// TArray<class UUI_HitRadar_Part_C*>      _ctrls                                                 (Parm, OutParm, ContainsInstancedReference)

void UUI_HitRadar_C::GetCtrls(struct FHitData& _hit, TArray<class UUI_HitRadar_Part_C*>* _ctrls) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "GetCtrls");

	Params::UI_HitRadar_C_GetCtrls Parms{};

	Parms._hit = std::move(_hit);

	UObject::ProcessEvent(Func, &Parms);

	_hit = std::move(Parms._hit);

	if (_ctrls != nullptr)
		*_ctrls = std::move(Parms._ctrls);
}


// Function UI_HitRadar.UI_HitRadar_C.GetPart
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// EBones                                  _bones                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUI_HitRadar_Part_C*              _ui                                                    (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_HitRadar_C::GetPart(EBones _bones, class UUI_HitRadar_Part_C** _ui) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_HitRadar_C", "GetPart");

	Params::UI_HitRadar_C_GetPart Parms{};

	Parms._bones = _bones;

	UObject::ProcessEvent(Func, &Parms);

	if (_ui != nullptr)
		*_ui = Parms._ui;
}

}

