#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_InGame_Chara_Skill_Detail_Item

#include "Basic.hpp"

#include "Stigma_structs.hpp"
#include "Engine_structs.hpp"
#include "BPGLib_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_InGame_Chara_Skill_Detail_Item.UI_InGame_Chara_Skill_Detail_Item_C
// 0x0260 (0x0750 - 0x04F0)
class UUI_InGame_Chara_Skill_Detail_Item_C final : public UPreviewableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Background_Img;                                    // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Desc_Text;                                         // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Detail_Main_Desc_Img;                              // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Title_Image;                                       // 0x0510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Title_Sub_Image;                                   // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Title_Sub_Panel;                                   // 0x0520(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Title_Sub_Text;                                    // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Title_Text;                                        // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_KeyMapping_C*                       UI_KeyMapping;                                     // 0x0538(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FActionGraphEntry                      TargetSkill;                                       // 0x0540(0x0208)(Edit, BlueprintVisible)
	EInputAction                                  KeyInputActionType;                                // 0x0748(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_InGame_Chara_Skill_Detail_Item(int32 EntryPoint);
	bool OnSynchronizeProperties();
	void SetTargetSkill(const struct FActionGraphEntry& Target);
	void UpdateSkill();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_InGame_Chara_Skill_Detail_Item_C">();
	}
	static class UUI_InGame_Chara_Skill_Detail_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_InGame_Chara_Skill_Detail_Item_C>();
	}
};
static_assert(alignof(UUI_InGame_Chara_Skill_Detail_Item_C) == 0x000008, "Wrong alignment on UUI_InGame_Chara_Skill_Detail_Item_C");
static_assert(sizeof(UUI_InGame_Chara_Skill_Detail_Item_C) == 0x000750, "Wrong size on UUI_InGame_Chara_Skill_Detail_Item_C");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, UberGraphFrame) == 0x0004F0, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, Background_Img) == 0x0004F8, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::Background_Img' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, Desc_Text) == 0x000500, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::Desc_Text' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, Detail_Main_Desc_Img) == 0x000508, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::Detail_Main_Desc_Img' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, Title_Image) == 0x000510, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::Title_Image' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, Title_Sub_Image) == 0x000518, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::Title_Sub_Image' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, Title_Sub_Panel) == 0x000520, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::Title_Sub_Panel' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, Title_Sub_Text) == 0x000528, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::Title_Sub_Text' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, Title_Text) == 0x000530, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::Title_Text' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, UI_KeyMapping) == 0x000538, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::UI_KeyMapping' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, TargetSkill) == 0x000540, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::TargetSkill' has a wrong offset!");
static_assert(offsetof(UUI_InGame_Chara_Skill_Detail_Item_C, KeyInputActionType) == 0x000748, "Member 'UUI_InGame_Chara_Skill_Detail_Item_C::KeyInputActionType' has a wrong offset!");

}

