#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_Option_General

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function UI_Option_General.UI_Option_General_C.BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature
// 0x000C (0x000C - 0x0000)
struct UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature final
{
public:
	class FName                                   _id;                                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         _idx;                                              // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature) == 0x000004, "Wrong alignment on UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature");
static_assert(sizeof(UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature) == 0x00000C, "Wrong size on UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature");
static_assert(offsetof(UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature, _id) == 0x000000, "Member 'UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature::_id' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature, _idx) == 0x000008, "Member 'UI_Option_General_C_BndEvt__Ctrl_Option_General_Ctrl_OptionDetailSelectTab_K2Node_ComponentBoundEvent_0_OnTabChanged__DelegateSignature::_idx' has a wrong offset!");

// Function UI_Option_General.UI_Option_General_C.ExecuteUbergraph_UI_Option_General
// 0x0058 (0x0058 - 0x0000)
struct UI_Option_General_C_ExecuteUbergraph_UI_Option_General final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0004(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_ComponentBoundEvent__id;                    // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent__idx;                   // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3694[0x4];                                     // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-69 ])
	double                                        CallFunc_Tick_Update__delta_ImplicitCast;          // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Option_General_C_ExecuteUbergraph_UI_Option_General) == 0x000008, "Wrong alignment on UI_Option_General_C_ExecuteUbergraph_UI_Option_General");
static_assert(sizeof(UI_Option_General_C_ExecuteUbergraph_UI_Option_General) == 0x000058, "Wrong size on UI_Option_General_C_ExecuteUbergraph_UI_Option_General");
static_assert(offsetof(UI_Option_General_C_ExecuteUbergraph_UI_Option_General, EntryPoint) == 0x000000, "Member 'UI_Option_General_C_ExecuteUbergraph_UI_Option_General::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_ExecuteUbergraph_UI_Option_General, K2Node_Event_MyGeometry) == 0x000004, "Member 'UI_Option_General_C_ExecuteUbergraph_UI_Option_General::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_ExecuteUbergraph_UI_Option_General, K2Node_Event_InDeltaTime) == 0x00003C, "Member 'UI_Option_General_C_ExecuteUbergraph_UI_Option_General::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_ExecuteUbergraph_UI_Option_General, K2Node_ComponentBoundEvent__id) == 0x000040, "Member 'UI_Option_General_C_ExecuteUbergraph_UI_Option_General::K2Node_ComponentBoundEvent__id' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_ExecuteUbergraph_UI_Option_General, K2Node_ComponentBoundEvent__idx) == 0x000048, "Member 'UI_Option_General_C_ExecuteUbergraph_UI_Option_General::K2Node_ComponentBoundEvent__idx' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_ExecuteUbergraph_UI_Option_General, CallFunc_Tick_Update__delta_ImplicitCast) == 0x000050, "Member 'UI_Option_General_C_ExecuteUbergraph_UI_Option_General::CallFunc_Tick_Update__delta_ImplicitCast' has a wrong offset!");

// Function UI_Option_General.UI_Option_General_C.Is Valid Offset
// 0x0088 (0x0088 - 0x0000)
struct UI_Option_General_C_Is_Valid_Offset final
{
public:
	class UUserWidget*                            _target_widget;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          _is_valid;                                         // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3695[0x7];                                     // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	double                                        _offset;                                           // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              CallFunc_GetCachedGeometry_ReturnValue;            // 0x0018(0x0038)(ConstParm, IsPlainOldData, NoDestructor)
	struct FVector2D                              CallFunc_GetLocalTopLeft_ReturnValue;              // 0x0050(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_Vector2DVector2D_ReturnValue;  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3696[0x7];                                     // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	double                                        CallFunc_BreakVector2D_X;                          // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3697[0x7];                                     // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Option_General_C_Is_Valid_Offset) == 0x000008, "Wrong alignment on UI_Option_General_C_Is_Valid_Offset");
static_assert(sizeof(UI_Option_General_C_Is_Valid_Offset) == 0x000088, "Wrong size on UI_Option_General_C_Is_Valid_Offset");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, _target_widget) == 0x000000, "Member 'UI_Option_General_C_Is_Valid_Offset::_target_widget' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, _is_valid) == 0x000008, "Member 'UI_Option_General_C_Is_Valid_Offset::_is_valid' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, _offset) == 0x000010, "Member 'UI_Option_General_C_Is_Valid_Offset::_offset' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, CallFunc_GetCachedGeometry_ReturnValue) == 0x000018, "Member 'UI_Option_General_C_Is_Valid_Offset::CallFunc_GetCachedGeometry_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, CallFunc_GetLocalTopLeft_ReturnValue) == 0x000050, "Member 'UI_Option_General_C_Is_Valid_Offset::CallFunc_GetLocalTopLeft_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, CallFunc_EqualEqual_Vector2DVector2D_ReturnValue) == 0x000060, "Member 'UI_Option_General_C_Is_Valid_Offset::CallFunc_EqualEqual_Vector2DVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, CallFunc_BreakVector2D_X) == 0x000068, "Member 'UI_Option_General_C_Is_Valid_Offset::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, CallFunc_BreakVector2D_Y) == 0x000070, "Member 'UI_Option_General_C_Is_Valid_Offset::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, CallFunc_Not_PreBool_ReturnValue) == 0x000078, "Member 'UI_Option_General_C_Is_Valid_Offset::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Is_Valid_Offset, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000080, "Member 'UI_Option_General_C_Is_Valid_Offset::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");

// Function UI_Option_General.UI_Option_General_C.MoveScroll
// 0x0008 (0x0008 - 0x0000)
struct UI_Option_General_C_MoveScroll final
{
public:
	int32                                         _idx;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Option_General_C_MoveScroll) == 0x000004, "Wrong alignment on UI_Option_General_C_MoveScroll");
static_assert(sizeof(UI_Option_General_C_MoveScroll) == 0x000008, "Wrong size on UI_Option_General_C_MoveScroll");
static_assert(offsetof(UI_Option_General_C_MoveScroll, _idx) == 0x000000, "Member 'UI_Option_General_C_MoveScroll::_idx' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_MoveScroll, K2Node_SwitchInteger_CmpSuccess) == 0x000004, "Member 'UI_Option_General_C_MoveScroll::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");

// Function UI_Option_General.UI_Option_General_C.OnSynchronizeProperties
// 0x0001 (0x0001 - 0x0000)
struct UI_Option_General_C_OnSynchronizeProperties final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Option_General_C_OnSynchronizeProperties) == 0x000001, "Wrong alignment on UI_Option_General_C_OnSynchronizeProperties");
static_assert(sizeof(UI_Option_General_C_OnSynchronizeProperties) == 0x000001, "Wrong size on UI_Option_General_C_OnSynchronizeProperties");
static_assert(offsetof(UI_Option_General_C_OnSynchronizeProperties, ReturnValue) == 0x000000, "Member 'UI_Option_General_C_OnSynchronizeProperties::ReturnValue' has a wrong offset!");

// Function UI_Option_General.UI_Option_General_C.Tick
// 0x003C (0x003C - 0x0000)
struct UI_Option_General_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Option_General_C_Tick) == 0x000004, "Wrong alignment on UI_Option_General_C_Tick");
static_assert(sizeof(UI_Option_General_C_Tick) == 0x00003C, "Wrong size on UI_Option_General_C_Tick");
static_assert(offsetof(UI_Option_General_C_Tick, MyGeometry) == 0x000000, "Member 'UI_Option_General_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Tick, InDeltaTime) == 0x000038, "Member 'UI_Option_General_C_Tick::InDeltaTime' has a wrong offset!");

// Function UI_Option_General.UI_Option_General_C.Tick Update
// 0x0018 (0x0018 - 0x0000)
struct UI_Option_General_C_Tick_Update final
{
public:
	double                                        _delta;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Current_offset;                                    // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Idx;                                               // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Option_General_C_Tick_Update) == 0x000008, "Wrong alignment on UI_Option_General_C_Tick_Update");
static_assert(sizeof(UI_Option_General_C_Tick_Update) == 0x000018, "Wrong size on UI_Option_General_C_Tick_Update");
static_assert(offsetof(UI_Option_General_C_Tick_Update, _delta) == 0x000000, "Member 'UI_Option_General_C_Tick_Update::_delta' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Tick_Update, Current_offset) == 0x000008, "Member 'UI_Option_General_C_Tick_Update::Current_offset' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Tick_Update, Idx) == 0x000010, "Member 'UI_Option_General_C_Tick_Update::Idx' has a wrong offset!");

// Function UI_Option_General.UI_Option_General_C.Update Active Navi Tab
// 0x0058 (0x0058 - 0x0000)
struct UI_Option_General_C_Update_Active_Navi_Tab final
{
public:
	float                                         Cur_scroll_offset;                                 // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScrollOffset_ReturnValue;              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Is_Valid_Offset__is_valid;                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3698[0x7];                                     // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	double                                        CallFunc_Is_Valid_Offset__offset;                  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Is_Valid_Offset__is_valid_1;              // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3699[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	double                                        CallFunc_Is_Valid_Offset__offset_1;                // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue_1;          // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue_1;            // 0x002B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScrollOffsetOfEnd_ReturnValue;         // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue_2;            // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_369A[0x6];                                     // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-69 ])
	double                                        CallFunc_Less_DoubleDouble_B_ImplicitCast;         // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_EqualEqual_DoubleDouble_B_ImplicitCast;   // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_B_ImplicitCast_1;       // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Option_General_C_Update_Active_Navi_Tab) == 0x000008, "Wrong alignment on UI_Option_General_C_Update_Active_Navi_Tab");
static_assert(sizeof(UI_Option_General_C_Update_Active_Navi_Tab) == 0x000058, "Wrong size on UI_Option_General_C_Update_Active_Navi_Tab");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, Cur_scroll_offset) == 0x000000, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::Cur_scroll_offset' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_GetScrollOffset_ReturnValue) == 0x000004, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_GetScrollOffset_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_Is_Valid_Offset__is_valid) == 0x000008, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_Is_Valid_Offset__is_valid' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_Is_Valid_Offset__offset) == 0x000010, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_Is_Valid_Offset__offset' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_Is_Valid_Offset__is_valid_1) == 0x000018, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_Is_Valid_Offset__is_valid_1' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_Is_Valid_Offset__offset_1) == 0x000020, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_Is_Valid_Offset__offset_1' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000028, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_Less_DoubleDouble_ReturnValue_1) == 0x000029, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_Less_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_NotEqual_IntInt_ReturnValue) == 0x00002A, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_NotEqual_IntInt_ReturnValue_1) == 0x00002B, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_NotEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_GetScrollOffsetOfEnd_ReturnValue) == 0x00002C, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_GetScrollOffsetOfEnd_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_EqualEqual_DoubleDouble_ReturnValue) == 0x000030, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_EqualEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_NotEqual_IntInt_ReturnValue_2) == 0x000031, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_NotEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_Less_DoubleDouble_B_ImplicitCast) == 0x000038, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_Less_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_EqualEqual_DoubleDouble_B_ImplicitCast) == 0x000040, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_EqualEqual_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_Less_DoubleDouble_B_ImplicitCast_1) == 0x000048, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_Less_DoubleDouble_B_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(UI_Option_General_C_Update_Active_Navi_Tab, CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast) == 0x000050, "Member 'UI_Option_General_C_Update_Active_Navi_Tab::CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");

}

