#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_PointingTarget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Stigma_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_PointingTarget.UI_PointingTarget_C
// 0x0058 (0x0598 - 0x0540)
class UUI_PointingTarget_C final : public UUI_FloatingGuideContainer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0540(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCanvasPanel*                           Main;                                              // 0x0548(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_Actor;                                         // 0x0550(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_AP;                                            // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_ArmorType;                                     // 0x0560(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_Distance;                                      // 0x0568(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_HP;                                            // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_MaxAP;                                         // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_MaxHP;                                         // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	double                                        Alpha;                                             // 0x0588(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACharaBase*                             TargetChara;                                       // 0x0590(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_PointingTarget(int32 EntryPoint);
	void Hide();
	void OnPointingActor(class AActor* _Actor);
	void Show(class ACharaBase* _chara);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void UpdateDistance();
	void UpdateTargetInfo();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_PointingTarget_C">();
	}
	static class UUI_PointingTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_PointingTarget_C>();
	}
};
static_assert(alignof(UUI_PointingTarget_C) == 0x000008, "Wrong alignment on UUI_PointingTarget_C");
static_assert(sizeof(UUI_PointingTarget_C) == 0x000598, "Wrong size on UUI_PointingTarget_C");
static_assert(offsetof(UUI_PointingTarget_C, UberGraphFrame) == 0x000540, "Member 'UUI_PointingTarget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, Main) == 0x000548, "Member 'UUI_PointingTarget_C::Main' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, TXT_Actor) == 0x000550, "Member 'UUI_PointingTarget_C::TXT_Actor' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, TXT_AP) == 0x000558, "Member 'UUI_PointingTarget_C::TXT_AP' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, TXT_ArmorType) == 0x000560, "Member 'UUI_PointingTarget_C::TXT_ArmorType' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, TXT_Distance) == 0x000568, "Member 'UUI_PointingTarget_C::TXT_Distance' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, TXT_HP) == 0x000570, "Member 'UUI_PointingTarget_C::TXT_HP' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, TXT_MaxAP) == 0x000578, "Member 'UUI_PointingTarget_C::TXT_MaxAP' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, TXT_MaxHP) == 0x000580, "Member 'UUI_PointingTarget_C::TXT_MaxHP' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, Alpha) == 0x000588, "Member 'UUI_PointingTarget_C::Alpha' has a wrong offset!");
static_assert(offsetof(UUI_PointingTarget_C, TargetChara) == 0x000590, "Member 'UUI_PointingTarget_C::TargetChara' has a wrong offset!");

}

