#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_RankingListView

#include "Basic.hpp"

#include "Stigma_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_RankingListView.UI_RankingListView_C
// 0x0000 (0x0528 - 0x0528)
class UUI_RankingListView_C final : public UUI_RankingListView
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_RankingListView_C">();
	}
	static class UUI_RankingListView_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_RankingListView_C>();
	}
};
static_assert(alignof(UUI_RankingListView_C) == 0x000008, "Wrong alignment on UUI_RankingListView_C");
static_assert(sizeof(UUI_RankingListView_C) == 0x000528, "Wrong size on UUI_RankingListView_C");

}

