#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_SocialPopup

#include "Basic.hpp"

#include "BPGLib_structs.hpp"
#include "Stigma_structs.hpp"


namespace SDK::Params
{

// Function UI_SocialPopup.UI_SocialPopup_C.OnSynchronizeProperties
// 0x0001 (0x0001 - 0x0000)
struct UI_SocialPopup_C_OnSynchronizeProperties final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_OnSynchronizeProperties) == 0x000001, "Wrong alignment on UI_SocialPopup_C_OnSynchronizeProperties");
static_assert(sizeof(UI_SocialPopup_C_OnSynchronizeProperties) == 0x000001, "Wrong size on UI_SocialPopup_C_OnSynchronizeProperties");
static_assert(offsetof(UI_SocialPopup_C_OnSynchronizeProperties, ReturnValue) == 0x000000, "Member 'UI_SocialPopup_C_OnSynchronizeProperties::ReturnValue' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.OnClick_SearchedUser
// 0x0048 (0x0048 - 0x0000)
struct UI_SocialPopup_C_OnClick_SearchedUser final
{
public:
	class UUserProfile*                           _user;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUserProfile*                           User;                                              // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FUserName                              CallFunc_GetNickname_ReturnValue;                  // 0x0010(0x0018)(ConstParm, HasGetValueTypeHash)
	struct FUserID                                CallFunc_GetUserID_ReturnValue;                    // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(EResultCode _rcode, struct FACK_Friend& _ack)> K2Node_CreateDelegate_OutputDelegate;              // 0x0030(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_OnClick_SearchedUser) == 0x000008, "Wrong alignment on UI_SocialPopup_C_OnClick_SearchedUser");
static_assert(sizeof(UI_SocialPopup_C_OnClick_SearchedUser) == 0x000048, "Wrong size on UI_SocialPopup_C_OnClick_SearchedUser");
static_assert(offsetof(UI_SocialPopup_C_OnClick_SearchedUser, _user) == 0x000000, "Member 'UI_SocialPopup_C_OnClick_SearchedUser::_user' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_OnClick_SearchedUser, User) == 0x000008, "Member 'UI_SocialPopup_C_OnClick_SearchedUser::User' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_OnClick_SearchedUser, CallFunc_GetNickname_ReturnValue) == 0x000010, "Member 'UI_SocialPopup_C_OnClick_SearchedUser::CallFunc_GetNickname_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_OnClick_SearchedUser, CallFunc_GetUserID_ReturnValue) == 0x000028, "Member 'UI_SocialPopup_C_OnClick_SearchedUser::CallFunc_GetUserID_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_OnClick_SearchedUser, K2Node_CreateDelegate_OutputDelegate) == 0x000030, "Member 'UI_SocialPopup_C_OnClick_SearchedUser::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_OnClick_SearchedUser, CallFunc_IsValid_ReturnValue) == 0x000040, "Member 'UI_SocialPopup_C_OnClick_SearchedUser::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.ExecuteUbergraph_UI_SocialPopup
// 0x0190 (0x0190 - 0x0000)
struct UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUserProfile* _brief_user)> K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUserProfile* _brief_user)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUserProfile* _brief_user)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUserProfile* _brief_user)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x0034(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsChecked_1;           // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsChecked;             // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4116[0x2];                                     // 0x0046(0x0002)(Fixing Size After Last Property [ Dumper-69 ])
	class FName                                   K2Node_ComponentBoundEvent__id;                    // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable;                                // 0x0050(0x0018)(ConstParm)
	struct FHoverMenuEntry                        K2Node_MakeStruct_HoverMenuEntry;                  // 0x0068(0x0058)()
	TDelegate<void(class UUserProfile* _user)>    K2Node_CreateDelegate_OutputDelegate_4;            // 0x00C0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AStigmaPlayerController*                CallFunc_GetLocalPlayerController_ReturnValue;     // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_1;                              // 0x00D8(0x0018)(ConstParm)
	class UUI_SearchUserPopup_C*                  CallFunc_Create_ReturnValue;                       // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPopupBase*                             CallFunc_DoModal_ReturnValue;                      // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UUserProfile* _brief_user)> K2Node_CreateDelegate_OutputDelegate_5;            // 0x0100(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	const class UUserProfile*                     K2Node_CustomEvent__brief_user;                    // 0x0110(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimatableWidget*                      K2Node_ComponentBoundEvent__widget_1;              // 0x0118(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent__select_1;              // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4117[0x7];                                     // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UAnimatableWidget*                      K2Node_ComponentBoundEvent__widget;                // 0x0128(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent__select;                // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4118[0x7];                                     // 0x0131(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UObject*                                K2Node_ComponentBoundEvent_item;                   // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bIsHovered;             // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4119[0x7];                                     // 0x0141(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UUserWidget*                            K2Node_ComponentBoundEvent_Widget;                 // 0x0148(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUI_BriefUserSlot_C*                    K2Node_DynamicCast_AsUI_Brief_User_Slot;           // 0x0150(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_411A[0x7];                                     // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UUserProfileRef*                        K2Node_DynamicCast_AsUser_Profile_Ref;             // 0x0160(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_411B[0x7];                                     // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	class UUserProfile*                           CallFunc_GetProfile_ReturnValue;                   // 0x0170(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	const class UUI_BriefUserSlot*                CallFunc_FindCurDisplayedUserSlot_ReturnValue;     // 0x0178(0x0008)(ConstParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUI_BriefUserSlot_C*                    K2Node_DynamicCast_AsUI_Brief_User_Slot_1;         // 0x0180(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup) == 0x000008, "Wrong alignment on UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup");
static_assert(sizeof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup) == 0x000190, "Wrong size on UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, EntryPoint) == 0x000000, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_CreateDelegate_OutputDelegate_1) == 0x000014, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_CreateDelegate_OutputDelegate_2) == 0x000024, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_CreateDelegate_OutputDelegate_3) == 0x000034, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent_bIsChecked_1) == 0x000044, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent_bIsChecked_1' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent_bIsChecked) == 0x000045, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent_bIsChecked' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent__id) == 0x000048, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent__id' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, Temp_text_Variable) == 0x000050, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_MakeStruct_HoverMenuEntry) == 0x000068, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_MakeStruct_HoverMenuEntry' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_CreateDelegate_OutputDelegate_4) == 0x0000C0, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, CallFunc_GetLocalPlayerController_ReturnValue) == 0x0000D0, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::CallFunc_GetLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, Temp_text_Variable_1) == 0x0000D8, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, CallFunc_Create_ReturnValue) == 0x0000F0, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, CallFunc_DoModal_ReturnValue) == 0x0000F8, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::CallFunc_DoModal_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_CreateDelegate_OutputDelegate_5) == 0x000100, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_CustomEvent__brief_user) == 0x000110, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_CustomEvent__brief_user' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent__widget_1) == 0x000118, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent__widget_1' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent__select_1) == 0x000120, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent__select_1' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent__widget) == 0x000128, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent__widget' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent__select) == 0x000130, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent__select' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent_item) == 0x000138, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent_item' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent_bIsHovered) == 0x000140, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent_bIsHovered' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_ComponentBoundEvent_Widget) == 0x000148, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_ComponentBoundEvent_Widget' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_DynamicCast_AsUI_Brief_User_Slot) == 0x000150, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_DynamicCast_AsUI_Brief_User_Slot' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_DynamicCast_bSuccess) == 0x000158, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_DynamicCast_AsUser_Profile_Ref) == 0x000160, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_DynamicCast_AsUser_Profile_Ref' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_DynamicCast_bSuccess_1) == 0x000168, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, CallFunc_GetProfile_ReturnValue) == 0x000170, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::CallFunc_GetProfile_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, CallFunc_FindCurDisplayedUserSlot_ReturnValue) == 0x000178, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::CallFunc_FindCurDisplayedUserSlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_DynamicCast_AsUI_Brief_User_Slot_1) == 0x000180, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_DynamicCast_AsUI_Brief_User_Slot_1' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup, K2Node_DynamicCast_bSuccess_2) == 0x000188, "Member 'UI_SocialPopup_C_ExecuteUbergraph_UI_SocialPopup::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.BriefUsreSlot_OnFriendDeleteRequested
// 0x0008 (0x0008 - 0x0000)
struct UI_SocialPopup_C_BriefUsreSlot_OnFriendDeleteRequested final
{
public:
	const class UUserProfile*                     _brief_user;                                       // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_BriefUsreSlot_OnFriendDeleteRequested) == 0x000008, "Wrong alignment on UI_SocialPopup_C_BriefUsreSlot_OnFriendDeleteRequested");
static_assert(sizeof(UI_SocialPopup_C_BriefUsreSlot_OnFriendDeleteRequested) == 0x000008, "Wrong size on UI_SocialPopup_C_BriefUsreSlot_OnFriendDeleteRequested");
static_assert(offsetof(UI_SocialPopup_C_BriefUsreSlot_OnFriendDeleteRequested, _brief_user) == 0x000000, "Member 'UI_SocialPopup_C_BriefUsreSlot_OnFriendDeleteRequested::_brief_user' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_RecentPlayer_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_RecentPlayer_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_RecentPlayer_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_RecentPlayer_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(sizeof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_RecentPlayer_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong size on UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_RecentPlayer_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_RecentPlayer_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature, bIsChecked) == 0x000000, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_RecentPlayer_K2Node_ComponentBoundEvent_9_OnCheckBoxComponentStateChanged__DelegateSignature::bIsChecked' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_Friend_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_Friend_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature final
{
public:
	bool                                          bIsChecked;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_Friend_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong alignment on UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_Friend_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(sizeof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_Friend_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature) == 0x000001, "Wrong size on UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_Friend_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_Friend_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature, bIsChecked) == 0x000000, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_PartyAcceptRangeToggle_Friend_K2Node_ComponentBoundEvent_8_OnCheckBoxComponentStateChanged__DelegateSignature::bIsChecked' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature final
{
public:
	class UObject*                                Item;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsHovered;                                        // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature) == 0x000008, "Wrong alignment on UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature");
static_assert(sizeof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature) == 0x000010, "Wrong size on UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature, Item) == 0x000000, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature::Item' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature, bIsHovered) == 0x000008, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_1_OnItemIsHoveredChangedDynamic__DelegateSignature::bIsHovered' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_14_OnListEntryGeneratedDynamic__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_14_OnListEntryGeneratedDynamic__DelegateSignature final
{
public:
	class UUserWidget*                            Widget;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_14_OnListEntryGeneratedDynamic__DelegateSignature) == 0x000008, "Wrong alignment on UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_14_OnListEntryGeneratedDynamic__DelegateSignature");
static_assert(sizeof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_14_OnListEntryGeneratedDynamic__DelegateSignature) == 0x000008, "Wrong size on UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_14_OnListEntryGeneratedDynamic__DelegateSignature");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_14_OnListEntryGeneratedDynamic__DelegateSignature, Widget) == 0x000000, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_LV_SlotPanel_New_K2Node_ComponentBoundEvent_14_OnListEntryGeneratedDynamic__DelegateSignature::Widget' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature final
{
public:
	class UAnimatableWidget*                      _widget;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          _select;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature) == 0x000008, "Wrong alignment on UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature");
static_assert(sizeof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature) == 0x000010, "Wrong size on UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature, _widget) == 0x000000, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature::_widget' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature, _select) == 0x000008, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_Ctrl_CommonButton_Intensity_K2Node_ComponentBoundEvent_17_DM_OnSelectEnd__DelegateSignature::_select' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.BndEvt__UI_SocialPopup_ConnectNotify_Switch_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct UI_SocialPopup_C_BndEvt__UI_SocialPopup_ConnectNotify_Switch_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature final
{
public:
	class FName                                   _id;                                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_ConnectNotify_Switch_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature) == 0x000004, "Wrong alignment on UI_SocialPopup_C_BndEvt__UI_SocialPopup_ConnectNotify_Switch_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature");
static_assert(sizeof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_ConnectNotify_Switch_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature) == 0x000008, "Wrong size on UI_SocialPopup_C_BndEvt__UI_SocialPopup_ConnectNotify_Switch_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_ConnectNotify_Switch_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature, _id) == 0x000000, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_ConnectNotify_Switch_K2Node_ComponentBoundEvent_11_OnClicked__DelegateSignature::_id' has a wrong offset!");

// Function UI_SocialPopup.UI_SocialPopup_C.BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature final
{
public:
	class UAnimatableWidget*                      _widget;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          _select;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature) == 0x000008, "Wrong alignment on UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature");
static_assert(sizeof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature) == 0x000010, "Wrong size on UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature, _widget) == 0x000000, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature::_widget' has a wrong offset!");
static_assert(offsetof(UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature, _select) == 0x000008, "Member 'UI_SocialPopup_C_BndEvt__UI_SocialPopup_AddFriendButton_K2Node_ComponentBoundEvent_15_DM_OnSelectEnd__DelegateSignature::_select' has a wrong offset!");

}

