#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_Tab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Stigma_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Tab.UI_Tab_C
// 0x0040 (0x0548 - 0x0508)
class UUI_Tab_C final : public UUI_TabBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0508(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHorizontalBox*                         H_Func_Container;                                  // 0x0510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Map_Deco_Bg;                                   // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMinimapView*                           MapView;                                           // 0x0520(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPanel_Tab_Players_C*                   Panel_Tab_Players;                                 // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_MapName;                                       // 0x0530(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          _IsFactionChanged;                                 // 0x0538(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A98[0x7];                                     // 0x0539(0x0007)(Fixing Size After Last Property [ Dumper-69 ])
	double                                        _TickLoopTime;                                     // 0x0540(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddActor(class AActor* _Actor);
	void Construct();
	void ExecuteUbergraph_UI_Tab(int32 EntryPoint);
	bool OnChangeActionSetting();
	bool OnDiscoverEnemy(class ACharaBase* _enemy, bool _discovered);
	bool OnShow(bool _show);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void Update_Spot(double _delta);
	void UpdateAppliedFunctions();
	void UpdateMapName();
	void UpdatePoints();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Tab_C">();
	}
	static class UUI_Tab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Tab_C>();
	}
};
static_assert(alignof(UUI_Tab_C) == 0x000008, "Wrong alignment on UUI_Tab_C");
static_assert(sizeof(UUI_Tab_C) == 0x000548, "Wrong size on UUI_Tab_C");
static_assert(offsetof(UUI_Tab_C, UberGraphFrame) == 0x000508, "Member 'UUI_Tab_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_Tab_C, H_Func_Container) == 0x000510, "Member 'UUI_Tab_C::H_Func_Container' has a wrong offset!");
static_assert(offsetof(UUI_Tab_C, Img_Map_Deco_Bg) == 0x000518, "Member 'UUI_Tab_C::Img_Map_Deco_Bg' has a wrong offset!");
static_assert(offsetof(UUI_Tab_C, MapView) == 0x000520, "Member 'UUI_Tab_C::MapView' has a wrong offset!");
static_assert(offsetof(UUI_Tab_C, Panel_Tab_Players) == 0x000528, "Member 'UUI_Tab_C::Panel_Tab_Players' has a wrong offset!");
static_assert(offsetof(UUI_Tab_C, TXT_MapName) == 0x000530, "Member 'UUI_Tab_C::TXT_MapName' has a wrong offset!");
static_assert(offsetof(UUI_Tab_C, _IsFactionChanged) == 0x000538, "Member 'UUI_Tab_C::_IsFactionChanged' has a wrong offset!");
static_assert(offsetof(UUI_Tab_C, _TickLoopTime) == 0x000540, "Member 'UUI_Tab_C::_TickLoopTime' has a wrong offset!");

}

