#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_Tooltip_GunPartsDesc

#include "Basic.hpp"

#include "UI_Tooltip_GunPartsDesc_classes.hpp"
#include "UI_Tooltip_GunPartsDesc_parameters.hpp"


namespace SDK
{

// Function UI_Tooltip_GunPartsDesc.UI_Tooltip_GunPartsDesc_C.InitWidget
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EGunPartsSlot                           _gun_parts_slot                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EGunType                                _gun_type                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Tooltip_GunPartsDesc_C::InitWidget(EGunPartsSlot _gun_parts_slot, EGunType _gun_type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Tooltip_GunPartsDesc_C", "InitWidget");

	Params::UI_Tooltip_GunPartsDesc_C_InitWidget Parms{};

	Parms._gun_parts_slot = _gun_parts_slot;
	Parms._gun_type = _gun_type;

	UObject::ProcessEvent(Func, &Parms);
}

}

