#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_Tooltip_GunSpecDetail

#include "Basic.hpp"

#include "UI_TooltipBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Tooltip_GunSpecDetail.UI_Tooltip_GunSpecDetail_C
// 0x0020 (0x0610 - 0x05F0)
class UUI_Tooltip_GunSpecDetail_C final : public UUI_TooltipBase_C
{
public:
	class UTextBlock*                             TXT_BoosterValue;                                  // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_PartsValue;                                    // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_PassiveValue;                                  // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_WeaponValue;                                   // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void InitWidget(const class FText& _Title, double _Weapon, double _passive, double _booster, double _parts);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Tooltip_GunSpecDetail_C">();
	}
	static class UUI_Tooltip_GunSpecDetail_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Tooltip_GunSpecDetail_C>();
	}
};
static_assert(alignof(UUI_Tooltip_GunSpecDetail_C) == 0x000008, "Wrong alignment on UUI_Tooltip_GunSpecDetail_C");
static_assert(sizeof(UUI_Tooltip_GunSpecDetail_C) == 0x000610, "Wrong size on UUI_Tooltip_GunSpecDetail_C");
static_assert(offsetof(UUI_Tooltip_GunSpecDetail_C, TXT_BoosterValue) == 0x0005F0, "Member 'UUI_Tooltip_GunSpecDetail_C::TXT_BoosterValue' has a wrong offset!");
static_assert(offsetof(UUI_Tooltip_GunSpecDetail_C, TXT_PartsValue) == 0x0005F8, "Member 'UUI_Tooltip_GunSpecDetail_C::TXT_PartsValue' has a wrong offset!");
static_assert(offsetof(UUI_Tooltip_GunSpecDetail_C, TXT_PassiveValue) == 0x000600, "Member 'UUI_Tooltip_GunSpecDetail_C::TXT_PassiveValue' has a wrong offset!");
static_assert(offsetof(UUI_Tooltip_GunSpecDetail_C, TXT_WeaponValue) == 0x000608, "Member 'UUI_Tooltip_GunSpecDetail_C::TXT_WeaponValue' has a wrong offset!");

}

