#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: UI_WelcomeBuff_Tooltip

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Stigma_structs.hpp"
#include "BPGLib_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_WelcomeBuff_Tooltip.UI_WelcomeBuff_Tooltip_C
// 0x0030 (0x0520 - 0x04F0)
class UUI_WelcomeBuff_Tooltip_C final : public UPreviewableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               Ovl_Container;                                     // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Tooltip_ItemID_Default_C*           Widget;                                            // 0x0500(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UOverlaySlot*                           Slot_ovl;                                          // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FItemIDRef_Function                    WelcomeBuffID;                                     // 0x0510(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_UI_WelcomeBuff_Tooltip(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_WelcomeBuff_Tooltip_C">();
	}
	static class UUI_WelcomeBuff_Tooltip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_WelcomeBuff_Tooltip_C>();
	}
};
static_assert(alignof(UUI_WelcomeBuff_Tooltip_C) == 0x000008, "Wrong alignment on UUI_WelcomeBuff_Tooltip_C");
static_assert(sizeof(UUI_WelcomeBuff_Tooltip_C) == 0x000520, "Wrong size on UUI_WelcomeBuff_Tooltip_C");
static_assert(offsetof(UUI_WelcomeBuff_Tooltip_C, UberGraphFrame) == 0x0004F0, "Member 'UUI_WelcomeBuff_Tooltip_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_WelcomeBuff_Tooltip_C, Ovl_Container) == 0x0004F8, "Member 'UUI_WelcomeBuff_Tooltip_C::Ovl_Container' has a wrong offset!");
static_assert(offsetof(UUI_WelcomeBuff_Tooltip_C, Widget) == 0x000500, "Member 'UUI_WelcomeBuff_Tooltip_C::Widget' has a wrong offset!");
static_assert(offsetof(UUI_WelcomeBuff_Tooltip_C, Slot_ovl) == 0x000508, "Member 'UUI_WelcomeBuff_Tooltip_C::Slot_ovl' has a wrong offset!");
static_assert(offsetof(UUI_WelcomeBuff_Tooltip_C, WelcomeBuffID) == 0x000510, "Member 'UUI_WelcomeBuff_Tooltip_C::WelcomeBuffID' has a wrong offset!");

}

