#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: WIDGET_FunctionWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Stigma_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WIDGET_FunctionWidget.WIDGET_FunctionWidget_C
// 0x0038 (0x0590 - 0x0558)
class UWIDGET_FunctionWidget_C final : public UUI_ActiveFunctionBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0558(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       UI_OnSpotlight;                                    // 0x0560(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       UI_OnShow;                                         // 0x0568(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCtrl_ItemIcon_C*                       Ctrl_ItemIcon;                                     // 0x0570(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Glow_Circle;                                       // 0x0578(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 M_Focus;                                           // 0x0580(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 M_OutGlow;                                         // 0x0588(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WIDGET_FunctionWidget(int32 EntryPoint);
	class UWidget* GetTooltipWidget();
	void Update();
	void UpdateUI();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WIDGET_FunctionWidget_C">();
	}
	static class UWIDGET_FunctionWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWIDGET_FunctionWidget_C>();
	}
};
static_assert(alignof(UWIDGET_FunctionWidget_C) == 0x000008, "Wrong alignment on UWIDGET_FunctionWidget_C");
static_assert(sizeof(UWIDGET_FunctionWidget_C) == 0x000590, "Wrong size on UWIDGET_FunctionWidget_C");
static_assert(offsetof(UWIDGET_FunctionWidget_C, UberGraphFrame) == 0x000558, "Member 'UWIDGET_FunctionWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWIDGET_FunctionWidget_C, UI_OnSpotlight) == 0x000560, "Member 'UWIDGET_FunctionWidget_C::UI_OnSpotlight' has a wrong offset!");
static_assert(offsetof(UWIDGET_FunctionWidget_C, UI_OnShow) == 0x000568, "Member 'UWIDGET_FunctionWidget_C::UI_OnShow' has a wrong offset!");
static_assert(offsetof(UWIDGET_FunctionWidget_C, Ctrl_ItemIcon) == 0x000570, "Member 'UWIDGET_FunctionWidget_C::Ctrl_ItemIcon' has a wrong offset!");
static_assert(offsetof(UWIDGET_FunctionWidget_C, Glow_Circle) == 0x000578, "Member 'UWIDGET_FunctionWidget_C::Glow_Circle' has a wrong offset!");
static_assert(offsetof(UWIDGET_FunctionWidget_C, M_Focus) == 0x000580, "Member 'UWIDGET_FunctionWidget_C::M_Focus' has a wrong offset!");
static_assert(offsetof(UWIDGET_FunctionWidget_C, M_OutGlow) == 0x000588, "Member 'UWIDGET_FunctionWidget_C::M_OutGlow' has a wrong offset!");

}

