#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: WIDGET_CharacterTitle

#include "Basic.hpp"

#include "Stigma_structs.hpp"
#include "BPGLib_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WIDGET_CharacterTitle.WIDGET_CharacterTitle_C
// 0x0018 (0x04F8 - 0x04E0)
class UWIDGET_CharacterTitle_C final : public UAnimatableWidget
{
public:
	class UTextBlock*                             TXT_CharaName;                                     // 0x04E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_Organization;                                  // 0x04E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	ECharaType                                    CharaType;                                         // 0x04F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool OnSynchronizeProperties();
	void SetCharaType(ECharaType _chara_type);
	void UpdateCharaType();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WIDGET_CharacterTitle_C">();
	}
	static class UWIDGET_CharacterTitle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWIDGET_CharacterTitle_C>();
	}
};
static_assert(alignof(UWIDGET_CharacterTitle_C) == 0x000008, "Wrong alignment on UWIDGET_CharacterTitle_C");
static_assert(sizeof(UWIDGET_CharacterTitle_C) == 0x0004F8, "Wrong size on UWIDGET_CharacterTitle_C");
static_assert(offsetof(UWIDGET_CharacterTitle_C, TXT_CharaName) == 0x0004E0, "Member 'UWIDGET_CharacterTitle_C::TXT_CharaName' has a wrong offset!");
static_assert(offsetof(UWIDGET_CharacterTitle_C, TXT_Organization) == 0x0004E8, "Member 'UWIDGET_CharacterTitle_C::TXT_Organization' has a wrong offset!");
static_assert(offsetof(UWIDGET_CharacterTitle_C, CharaType) == 0x0004F0, "Member 'UWIDGET_CharacterTitle_C::CharaType' has a wrong offset!");

}

