#pragma once

/*
* SDK generated by Dumper-69
*
* https://github.com/Encryqed/Dumper-69
*/

// Package: WIDGET_BulletTipSelection

#include "Basic.hpp"

#include "Stigma_structs.hpp"


namespace SDK::Params
{

// Function WIDGET_BulletTipSelection.WIDGET_BulletTipSelection_C.ExecuteUbergraph_WIDGET_BulletTipSelection
// 0x0008 (0x0008 - 0x0000)
struct WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBulletTip                                    K2Node_ComponentBoundEvent_bullet_tip_3;           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBulletTip                                    K2Node_ComponentBoundEvent_bullet_tip_2;           // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBulletTip                                    K2Node_ComponentBoundEvent_bullet_tip_1;           // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EBulletTip                                    K2Node_ComponentBoundEvent_bullet_tip;             // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection) == 0x000004, "Wrong alignment on WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection");
static_assert(sizeof(WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection) == 0x000008, "Wrong size on WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection");
static_assert(offsetof(WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection, EntryPoint) == 0x000000, "Member 'WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection::EntryPoint' has a wrong offset!");
static_assert(offsetof(WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection, K2Node_ComponentBoundEvent_bullet_tip_3) == 0x000004, "Member 'WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection::K2Node_ComponentBoundEvent_bullet_tip_3' has a wrong offset!");
static_assert(offsetof(WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection, K2Node_ComponentBoundEvent_bullet_tip_2) == 0x000005, "Member 'WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection::K2Node_ComponentBoundEvent_bullet_tip_2' has a wrong offset!");
static_assert(offsetof(WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection, K2Node_ComponentBoundEvent_bullet_tip_1) == 0x000006, "Member 'WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection::K2Node_ComponentBoundEvent_bullet_tip_1' has a wrong offset!");
static_assert(offsetof(WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection, K2Node_ComponentBoundEvent_bullet_tip) == 0x000007, "Member 'WIDGET_BulletTipSelection_C_ExecuteUbergraph_WIDGET_BulletTipSelection::K2Node_ComponentBoundEvent_bullet_tip' has a wrong offset!");

// Function WIDGET_BulletTipSelection.WIDGET_BulletTipSelection_C.BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_T_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_T_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature final
{
public:
	EBulletTip                                    bullet_tip;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_T_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature) == 0x000001, "Wrong alignment on WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_T_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature");
static_assert(sizeof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_T_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature) == 0x000001, "Wrong size on WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_T_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature");
static_assert(offsetof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_T_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature, bullet_tip) == 0x000000, "Member 'WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_T_K2Node_ComponentBoundEvent_1_OnClick__DelegateSignature::bullet_tip' has a wrong offset!");

// Function WIDGET_BulletTipSelection.WIDGET_BulletTipSelection_C.BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_HP_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_HP_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature final
{
public:
	EBulletTip                                    bullet_tip;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_HP_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature) == 0x000001, "Wrong alignment on WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_HP_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature");
static_assert(sizeof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_HP_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature) == 0x000001, "Wrong size on WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_HP_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature");
static_assert(offsetof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_HP_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature, bullet_tip) == 0x000000, "Member 'WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_HP_K2Node_ComponentBoundEvent_2_OnClick__DelegateSignature::bullet_tip' has a wrong offset!");

// Function WIDGET_BulletTipSelection.WIDGET_BulletTipSelection_C.BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_FMJ_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_FMJ_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature final
{
public:
	EBulletTip                                    bullet_tip;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_FMJ_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature) == 0x000001, "Wrong alignment on WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_FMJ_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature");
static_assert(sizeof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_FMJ_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature) == 0x000001, "Wrong size on WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_FMJ_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature");
static_assert(offsetof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_FMJ_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature, bullet_tip) == 0x000000, "Member 'WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_FMJ_K2Node_ComponentBoundEvent_3_OnClick__DelegateSignature::bullet_tip' has a wrong offset!");

// Function WIDGET_BulletTipSelection.WIDGET_BulletTipSelection_C.BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_AP_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_AP_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature final
{
public:
	EBulletTip                                    bullet_tip;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_AP_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature) == 0x000001, "Wrong alignment on WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_AP_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");
static_assert(sizeof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_AP_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature) == 0x000001, "Wrong size on WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_AP_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature");
static_assert(offsetof(WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_AP_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature, bullet_tip) == 0x000000, "Member 'WIDGET_BulletTipSelection_C_BndEvt__WIDGET_BulletTipSelection_Btn_BulletTip_AP_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature::bullet_tip' has a wrong offset!");

}

